### ISSUE TITLE
Bridge.get_core() raises Exception

### ISSUE THREAD

**Issue by nanthony21** [micro-manager/pycro-manager#12]
Here is the traceback
```
Traceback (most recent call last):
  File "C:/Users/nicke/Documents/git/pycro-manager/pycromanager/core.py", line 463, in <module>
    c = b.get_core()
  File "C:/Users/nicke/Documents/git/pycro-manager/pycromanager/core.py", line 198, in get_core
    self.core = self.construct_java_object('mmcorej.CMMCore')
  File "C:/Users/nicke/Documents/git/pycro-manager/pycromanager/core.py", line 165, in construct_java_object
    convert_camel_case=self._convert_camel_case)
  File "C:/Users/nicke/Documents/git/pycro-manager/pycromanager/core.py", line 233, in __init__
    exec('setattr(self, method_name_modified, MethodType(fn, self))')
  File "<string>", line 1, in <module>
NameError: name 'MethodType' is not defined
```

This appears to be caused by the usage `exec`. I'm not sure I understand the reasoning for using `exec` but I would caution against it if it's not absolutely necessary.

**Comment by henrypinkard** [comment]
Can you post full reproducing example?

**Comment by nanthony21** [comment]
Apologies, I had used PyCharm's automatic refactoring and it missed the import of `types.MethodType`
