### ISSUE TITLE
ZMQ Error when running multiple acquisition hooks on windows

### ISSUE THREAD

**Issue by henrypinkard** [micro-manager/pycro-manager#169]
### Bug report

The following code gives a cryptic ZMQ error on Windows. It seems to be related to garbage collecting a second core object with an acquisition hook. It only triggers when there are two acquisition hooks. It is not possible to set a breakpoint to see what is going on inside the function when it happens for some reason. It seems as though this may be a ZMQ bug. Luckily, it doesnt cause any actual problems in the current example

```python
from pycromanager import Bridge, Acquisition

def hook_fn(event,bridge,event_queue):

    core = bridge.get_core()
    return event

with Acquisition(directory=save_directory, name=save_name, post_hardware_hook_fn=hook_fn, 
                    post_camera_hook_fn=hook_fn, ) as acq: 
    acq.acquire(events)

```

```
Traceback (most recent call last):
  File "C:\Users\dpsheph1\Anaconda3\envs\pycro_test\lib\site-packages\pycromanager-0.5.0-py3.8.egg\pycromanager\core.py", line 345, in __del__
  File "C:\Users\dpsheph1\Anaconda3\envs\pycro_test\lib\site-packages\pycromanager-0.5.0-py3.8.egg\pycromanager\core.py", line 336, in _close
  File "C:\Users\dpsheph1\Anaconda3\envs\pycro_test\lib\site-packages\pycromanager-0.5.0-py3.8.egg\pycromanager\core.py", line 85, in receive
  File "zmq\backend\cython\socket.pyx", line 791, in zmq.backend.cython.socket.Socket.recv
  File "zmq\backend\cython\socket.pyx", line 824, in zmq.backend.cython.socket.Socket.recv
  File "zmq\backend\cython\socket.pyx", line 135, in zmq.backend.cython.socket._check_closed
zmq.error.ZMQError: Unknown error
```

**Comment by henrypinkard** [comment]
probably fixed by https://github.com/micro-manager/pycro-manager/pull/299, but unverified

**Comment by henrypinkard** [comment]
Seems to be fixed
