### ISSUE TITLE
Best way to close Pycromanager

### ISSUE THREAD

**Issue by dangerousMoron** [micro-manager/pycro-manager#205]
Hi and thank you for this wonderful piece of software! 

I'm working with pycromanager and Ipython/Spyder and I'm having a bit of trouble properly disconnecting micromanager from my python instance.  

If I close micromanager, and then re-open, I get the following error:
 
`Exception: java.lang.NullPointerException
	at org.micromanager.internal.zmq.ZMQServer.runMethod(ZMQServer.java:325)
	at org.micromanager.internal.zmq.ZMQServer.parseAndExecuteCommand(ZMQServer.java:394)
	at org.micromanager.internal.zmq.ZMQServer.lambda$initialize$1(ZMQServer.java:103)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

I'd ideally like to be able to exit micro-manager, restart it, and then disconnect and re-initialize the python pycromanager objects without having to restart the IPython Kernel. 

Is this possible? Thanks!

**Comment by henrypinkard** [comment]
Hello @dangerousMoron, you're welcome, glad you like it!

With the caveat that I dont quite understand why you would want to do this, the answer is probably no. All the objects pycro-manager creates exist in the Java Virtual Machine that gets destroyed when you shut down MM.

It should be possible that you close and open MM and and reconnect from the same python session and re-create all your obejcts from scratch though

**Comment by henrypinkard** [comment]
If the latter, make sure all your python objects get garbage collected -- ie set all the references of pycromanager objects to `None`

**Comment by dangerousMoron** [comment]
Thank you for your assistance, I will play around a bit!

**Comment by henrypinkard** [comment]
Assuming this is solved, feel free to reopenif not
