### ISSUE TITLE
java.lang.ClassCastException

### ISSUE THREAD

**Issue by nanthony21** [micro-manager/pycro-manager#21]
I was trying to run some of the tests but I ran into this error.
I've seen this error on `multi_d_acq`  and `magellan_acq`, though it may also appear on other tests.

Traceback here:
```
Traceback (most recent call last):
  File "C:/Users/nicke/Documents/git/pycro-manager/test/multi_d_acq.py", line 5, in <module>
    with Acquisition(directory='/Users/henrypinkard/megllandump', name='tcz_acq') as acq:
  File "C:\Users\nicke\Documents\git\pycro-manager\pycromanager\acquire.py", line 146, in __init__
    acq_manager = self.bridge.construct_java_object('org.micromanager.remote.RemoteAcquisitionFactory', args=[core])
  File "C:\Users\nicke\Documents\git\pycro-manager\pycromanager\core.py", line 173, in construct_java_object
    serialized_object = self._master_socket.receive()
  File "C:\Users\nicke\Documents\git\pycro-manager\pycromanager\core.py", line 87, in receive
    self._check_exception(message)
  File "C:\Users\nicke\Documents\git\pycro-manager\pycromanager\core.py", line 92, in _check_exception
    raise Exception(response['value'])
Exception: java.lang.ClassCastException: java.lang.Package cannot be cast to java.lang.Comparable
```

As a sidenote, it would be nice to move towards having tests formatted to run in something like PyTest so that testing can be done more automatically.

**Comment by henrypinkard** [comment]
Should be fixed last night by https://github.com/micro-manager/pycro-manager/pull/20/files, try latest nightly build

**Comment by henrypinkard** [comment]
And definitely agree that more automated testing would be great
