### ISSUE TITLE
installation verify error

### ISSUE THREAD

**Issue by yichun463** [micro-manager/pycro-manager#290]
### Bug report

**Bug summary**

Installation verify code in python returns weird error.
**Code for reproduction**

```python
from pycromanager import Bridge
bridge = Bridge()
print(bridge.get_core())


```

**Expected outcome**

pycromanager.core.mmcorej_CMMCore object at 0x7fe32824a208

**Actual outcome**

Traceback (most recent call last):
  File "<input>", line 4, in <module>
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib\site-packages\pycromanager\core.py", line 348, in get_core
    self.core = self.construct_java_object("mmcorej.CMMCore")
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib\site-packages\pycromanager\core.py", line 284, in construct_java_object
    self._master_socket.send(message)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib\site-packages\pycromanager\core.py", line 115, in send
    self._socket.send_multipart(message_parts)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib\site-packages\zmq\sugar\socket.py", line 555, in send_multipart
    return self.send(msg_parts[-1], flags, copy=copy, track=track)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib\site-packages\zmq\sugar\socket.py", line 505, in send
    return super(Socket, self).send(data, flags=flags, copy=copy, track=track)
  File "zmq\backend\cython\socket.pyx", line 718, in zmq.backend.cython.socket.Socket.send
  File "zmq\backend\cython\socket.pyx", line 765, in zmq.backend.cython.socket.Socket.send
  File "zmq\backend\cython\socket.pyx", line 247, in zmq.backend.cython.socket._send_copy
  File "zmq\backend\cython\socket.pyx", line 242, in zmq.backend.cython.socket._send_copy
  File "zmq\backend\cython\checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Operation cannot be accomplished in current state
![image](https://user-images.githubusercontent.com/66891774/120775913-3c08c880-c556-11eb-9c9f-6da154d3dfce.png)

**Version Info**

  * Operating system: Win10
  * pycromanager version: 2.4.0 (as following)
  *
![image](https://user-images.githubusercontent.com/66891774/120775076-71f97d00-c555-11eb-8acf-c6dde9dd339e.png)

  * MicroManager version:  2.0.0-gamma1 20210602
  * Python version: Python 3.8
  * Python environment (command line, IDE, Jupyter notebook, etc) IDE: Pycharm

**Comment by henrypinkard** [comment]
Something going wrong with the communication library pycromanager uses under the hood. My first thought would be to make sure you're not accidentally running multiple instances of something. Maybe try shutting down everything (including computer) and running from a fresh environment

**Comment by yichun463** [comment]
Thank you for your reply. It seems still not work after restarting everything.So Is there another way to start a fresh environment?

**Comment by henrypinkard** [comment]
Not that I can think of.

This is strange because it seems like the bridge is successfully connecting, but then not working when you try to get the core. If you try:

```python
bridge = Bridge(debug=True)
```

Maybe something informative will be printed?

**Comment by yichun463** [comment]
Thank you for your patience. It works after I reinstall the pycromanager.
![image](https://user-images.githubusercontent.com/66891774/121620088-4833df00-ca9c-11eb-99ce-a217bed2290d.png)
