### ISSUE TITLE
Exception Errors when Calling Acquisition()

### ISSUE THREAD

**Issue by nmarosan** [micro-manager/pycro-manager#310]
Hi, we are trying to run an acquisition following this example: https://pycro-manager.readthedocs.io/en/latest/apis.html#acquisition-event-specification and are getting lots of exception errors. We have the newest versions of micromanager (21-07-13) and pycromanager (0.13.1) installed--when we verified that the installation worked with Bridge, we got the correct output. Any suggestions or advice on where these issues stem from? Additionally, when we ran the multi_d_acquisiton_events(), there were no errors, just when we tried to call the Acquisition().

```python
with Acquisition(save_path, 'acquisition_name') as acq:
    events = multi_d_acquisition_events(
        num_time_points=1, 
        time_interval_s=0, 
        channel_group='Channel', 
        channels = channels,
        channel_exposures_ms = [100, 100], 
        xy_postions = xy_pos, 
        order='tpc'
    )
```
```python
Exception: java.lang.NullPointerException
	at org.micromanager.internal.zmq.ZMQServer.getParamCombos(ZMQServer.java:213)
	at org.micromanager.internal.zmq.ZMQServer.runConstructor(ZMQServer.java:291)
	at org.micromanager.internal.zmq.ZMQServer.parseAndExecuteCommand(ZMQServer.java:387)
	at org.micromanager.internal.zmq.ZMQServer.lambda$initialize$1(ZMQServer.java:108)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Any advice would be helpful, thanks!

**Comment by henrypinkard** [comment]
I'm not able to test from the code you posted alone. Could you also include the values used for `channels` and `xy_pos`

**Comment by nmarosan** [comment]
Hi Henry, sorry about that. We used:
```python
xy_pos = [[-29995.7,-3105.9], [-30398.3,-3617.2]]
channels = ['488(10)_gfp(525-30)_200ms', 'BF_gfp(525-30)_30ms']
```
These are some of the values were testing including the names of the different lasers as we have them labeled in micromanager.

**Comment by henrypinkard** [comment]
I don't have any issues with this code (except that it doesnt call `acq.acquire(events)` and `xy_positions` is misspelled). But after fixing that it works fine. Are you able to reproduce this with the MM demo configuration?
