### ISSUE TITLE
core.load_slm_sequence(): Unknown input type java.util.List?

### ISSUE THREAD

**Issue by jblugagne** [micro-manager/pycro-manager#319]
### Bug report

**Bug summary**

Hi,

When trying to use core.load_slm_sequence() with a list of uint8 flattened images, I get the error below. It looks like the `java.util.List` data type that the loadSLMSequence method on the java side expects is not in the _JAVA_TYPE_NAME_TO_CASTABLE_PYTHON_TYPE dictionary. I've tried a few different ways to pass this data either as a completely numpy array, list of lists, but without success.

My SLM is a Mightex Polygon400, and I have used this method through Matlab often, with flattened uint8 images stacked into an ArrayList.

**Code for reproduction**

```python
dmd = core.get_slm_device()
shape = (core.get_slm_height(dmd),core.get_slm_width(dmd))
images = np.random.rand(20,shape[0],shape[1])*255
images_1D = [i.ravel().astype(np.uint8) for i in images]
core.load_slm_sequence(dmd, images_1D)
```

**Expected outcome**

The image sequence loads to the DMD

**Actual outcome**

I get the following error:
```python
 Traceback (most recent call last):

  File "C:\Users\System 6\Documents\pycromanager\Platform.py", line 409, in <module>
    core.load_slm_sequence(dmd, images_1D)

  File "C:\Anaconda\envs\pycromanager_env\lib\site-packages\pycromanager\core.py", line 432, in <lambda>
    ): instance._translate_call(signatures_list, args)

  File "C:\Anaconda\envs\pycromanager_env\lib\site-packages\pycromanager\core.py", line 540, in _translate_call
    valid_method_spec, deserialize_types = _check_method_args(method_specs, fn_args)

  File "C:\Anaconda\envs\pycromanager_env\lib\site-packages\pycromanager\core.py", line 699, in _check_method_args
    if _check_single_method_spec(method_spec, fn_args):

  File "C:\Anaconda\envs\pycromanager_env\lib\site-packages\pycromanager\core.py", line 674, in _check_single_method_spec
    for acceptable_type in _JAVA_TYPE_NAME_TO_CASTABLE_PYTHON_TYPE[arg_java_type]

KeyError: 'java.util.List'
```
**Version Info**

  * Operating system: Windows10.0.19042 Build 19042
  * pycromanager version: 0.13.2
  * MicroManager version: 2.0.0-gamma1 20210712
  * Python version: 3.9.7
  * Python environment: Spyder 5.1.3, ipython 7.27.0

**Comment by henrypinkard** [comment]
You need to explicitly create the Java List object. Haven't tested but I think something like this should do the trick:

```python
java_list = bridge.construct_java_object('java.util.ArrayList')
java_list.put(...
```

**Comment by jblugagne** [comment]
Ah I see! I'll test this as soon as I have access to the microscope and let you know thanks.

**Comment by jblugagne** [comment]
Thank you for your suggestion, I'm making some progress:

When I run the following:
```python
images_1D = bridge.construct_java_object('java.util.ArrayList')
for _ in range(20):
    img = np.random.randint(0,255,size=dmd_shape,dtype=np.uint8)
    images_1D.add(img.ravel())

# load images:
core.load_slm_sequence(dmd_name,images_1D)
```

I get this error:
```python
Traceback (most recent call last):

  File "C:\Users\SYSTEM~1\AppData\Local\Temp/ipykernel_8116/1272827267.py", line 7, in <module>
    core.load_slm_sequence(dmd_name,images_1D)

  File "C:\Anaconda\envs\pycromanager_env\lib\site-packages\pycromanager\core.py", line 432, in <lambda>
    ): instance._translate_call(signatures_list, args)

  File "C:\Anaconda\envs\pycromanager_env\lib\site-packages\pycromanager\core.py", line 554, in _translate_call
    return self._deserialize(self._socket.receive())

  File "C:\Anaconda\envs\pycromanager_env\lib\site-packages\pycromanager\core.py", line 168, in receive
    self._check_exception(message)

  File "C:\Anaconda\envs\pycromanager_env\lib\site-packages\pycromanager\core.py", line 173, in _check_exception
    raise Exception(response["value"])

Exception: java.lang.RuntimeException: No Matching method found with argumetn types
	at org.micromanager.internal.zmq.ZMQServer.runMethod(ZMQServer.java:340)
	at org.micromanager.internal.zmq.ZMQServer.parseAndExecuteCommand(ZMQServer.java:401)
	at org.micromanager.internal.zmq.ZMQServer.lambda$initialize$1(ZMQServer.java:108)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

For reference, the following (dirty) beanshell script works fine via the MM interface and I can cycle through the ON/OFF frames with the last "CommandTrigger" line:
```java
dmd_name = mmc.getSLMDevice();
dmd_height = mmc.getSLMHeight(dmd_name);
dmd_width = mmc.getSLMWidth(dmd_name);
// OFF frame:
byte[] img0 = new byte[dmd_height*dmd_width];
for (int i =0; i< img0.length; i++){
	img0[i]=(byte)0;
}
// ON frame:
byte[] img1 = new byte[dmd_height*dmd_width];
for (int i =0; i< img1.length; i++){
	img1[i]=(byte)255;
}
// Create Array list and alternate ON/OFF frames:
images_1D = new java.util.ArrayList();
for (int i =0; i< 10; i++){
	images_1D.add(img1);
	images_1D.add(img0);
}
// Load to DMD, Start sequence, trigger to 1st frame:
mmc.loadSLMSequence(dmd_name,images_1D);
mmc.startSLMSequence(dmd_name);
mmc.setProperty(dmd_name,(String)"CommandTrigger",1);
```
With my limited knowledge of java, this seems to be the same type of data as what I am trying to send through the bridge. Do you know what is going on here?

This is the message that is being sent to the socket in instance._translate_call() if it is of any help:
```python
{'command': 'run-method', 'hash-code': '6309eecfd68fb379-ee3a-4e05-82f2-675b1dcf9e95', 'name': 'loadSLMSequence', 'argument-types': ['java.lang.String', 'java.util.List'], 'argument-deserialization-types': ['java.lang.String', 'java.util.List'], 'arguments': ['MightexPolygon', {'hash-code': '5a593d6de1b594b0-efe2-4a2c-b227-e363dc524864'}]}
```

**Comment by henrypinkard** [comment]
There might be some confusion in the Java-Python bridge where it's not correctly recognizing that it's a `ArrayList<byte[]>` because it's being sent as an `ArrayList<Object>`. I'd have to dig into this a bit to verify.

**Comment by jblugagne** [comment]
I see, thank you for your help, and let me know if there's anything I can test for you.

**Comment by henrypinkard** [comment]
Sounds good, will try to take a stab at it in not too long
