### ISSUE TITLE
Burst Acquisition does not complete

### ISSUE THREAD

**Issue by girurkrk91** [micro-manager/pycro-manager#322]
**Bug summary**

Burst acquisition does not complete when called using Acquisition.acquire(). The acquisition seems to collect all the requested frames, but refuses to exit while being stuck at await_completion. For example, in the attached script, all 30 frames are acquired as evident from the micromanager display pop-up, but the script doesn't conclude. I have no problems running burst acquisition with time interval = 0 or regular timelapses from the micromanager gui directly. I also have no problems running non-burst timelapses from pycromanager. I am unable to replicate this bug with the micro-manager demo configuration.

**Code for reproduction**

```python
from pycromanager import (Acquisition, Bridge, multi_d_acquisition_events)

bridge = Bridge(debug=False)
core = bridge.get_core()

time_interval = 0

core.set_property('Camera', 'Exposure', 10)

timelapse_events = multi_d_acquisition_events(30,time_interval)

with Acquisition(directory=r'C:\Users\Girish', name='test', show_display=True,debug=False,core_log_debug=True) as acq:
    acq.acquire(timelapse_events)
```

**Expected outcome**

The acquisition completes successfully

**Actual outcome**

All frames are acquired, however, the micro-manager pop-up window never transitions from Running to Finished. Script does not complete.

**Version Info**
  * Operating system: Windows 10, 64 bit
  * pycromanager version: 0.13.2
  * MicroManager version: 2.0.0
  * Python version: 3.9.6
  * Python environment (command line, IDE, Jupyter notebook, etc) command line

**Comment by henrypinkard** [comment]
Yeah that's weird. They dont use the same acq engine, but the functionality should be identical. Its possible theres some weird edge case not accounted for in the pycromanager one that only services with your specific camera.

It finishes when a whole shutdown process has occurred including saving all the data and grabbing all the expected images from the camera. It might be that theres an exception arising somewhere in there thats not be handled/propagated to an error message properly. Youve got `core_log_debug` on i see. Is there anything suspicious in the Micro-manager core log?

**Comment by girurkrk91** [comment]
These are the last few lines in the core log before I interrupt acquisition. There are no messages after the 30th image is written.
```
                                    [       ] writing_queue_size= 0
2021-10-05T17:01:27.921600 tid4668 [IFO,App] write_image_time_1856900
2021-10-05T17:01:27.938831 tid10884 [IFO,dev:Camera] Frame callback: 1920 X 1080, frame: 29, buffer: 1920X1080
2021-10-05T17:01:27.951820 tid14404 [IFO,App] Adding image channel  0,  time  28,  
                                    [       ] writing_queue_size= 0
2021-10-05T17:01:27.953815 tid4668 [IFO,App] write_image_time_1832000
2021-10-05T17:01:27.970718 tid10884 [IFO,dev:Camera] Frame callback: 1920 X 1080, frame: 30, buffer: 1920X1080
2021-10-05T17:01:27.984157 tid14404 [IFO,App] Adding image channel  0,  time  29,  
                                    [       ] writing_queue_size= 0
2021-10-05T17:01:27.989128 tid4668 [IFO,App] write_image_time_3990700
```

I also set debug=True in acquisition and I saw a timeout reported in stdout -
```
DEBUG, sending: {'command': 'run-method', 'hash-code': '1c941cb17b39e98a-fdd8-40f0-a674-be6acc5a8c7f', 'name': 'getEventPort', 'argument-types': [], 'argument-deserialization-types': [], 'arguments': []}
DEBUG, recieved: {'type': 'primitive', 'value': 4830}
DEBUG, sending: {'command': 'destructor', 'hash-code': '1216c3dd63131c71-fa19-436d-b1bf-10781d123d57'}
Exception in thread Event sending:
Traceback (most recent call last):
  File "C:\Users\Girish\.conda\envs\umanager\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\Girish\.conda\envs\umanager\lib\threading.py", line 910, in run
DEBUG, recieved: {'type': 'none'}
DEBUG, sending: {'command': 'destructor', 'hash-code': '4dd65057598a6077-ee9a-4a1c-9074-dae33bf6ef3a'}
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Girish\.conda\envs\umanager\lib\site-packages\pycromanager\acquire.py", line 111, in _event_sending_fn
DEBUG, recieved: {'type': 'none'}
DEBUG, sending: {'command': 'run-method', 'hash-code': '1c941cb17b39e98a-fdd8-40f0-a674-be6acc5a8c7f', 'name': 'isFinished', 'argument-types': [], 'argument-deserialization-types': [], 'arguments': []}
    with Bridge(debug=debug, port=bridge_port, timeout=bridge_timeout) as bridge:
  File "C:\Users\Girish\.conda\envs\umanager\lib\site-packages\pycromanager\core.py", line 250, in __init__
DEBUG, recieved: {'type': 'primitive', 'value': False}
    raise TimeoutError(
TimeoutError: Socket timed out after True milliseconds. Is Micro-Manager running and is the ZMQ server on 4827 option enabled?
DEBUG, sending: {'command': 'run-method', 'hash-code': '1c941cb17b39e98a-fdd8-40f0-a674-be6acc5a8c7f', 'name': 'isFinished', 'argument-types': [], 'argument-deserialization-types': [], 'arguments': []}
DEBUG, recieved: {'type': 'primitive', 'value': False}
DEBUG, sending: {'command': 'run-method', 'hash-code': '1c941cb17b39e98a-fdd8-40f0-a674-be6acc5a8c7f', 'name': 'isFinished', 'argument-types': [], 'argument-deserialization-types': [], 'arguments': []}
DEBUG, recieved: {'type': 'primitive', 'value': False}
DEBUG, sending: {'command': 'run-method', 'hash-code': '1c941cb17b39e98a-fdd8-40f0-a674-be6acc5a8c7f', 'name': 'isFinished', 'argument-types': [], 'argument-deserialization-types': [], 'arguments': []}
DEBUG, recieved: {'type': 'primitive', 'value': False}
DEBUG, sending: {'command': 'run-method', 'hash-code': '1c941cb17b39e98a-fdd8-40f0-a674-be6acc5a8c7f', 'name': 'isFinished', 'argument-types': [], 'argument-deserialization-types': [], 'arguments': []}
DEBUG, recieved: {'type': 'primitive', 'value': False}
DEBUG, sending: {'command': 'run-method', 'hash-code': '1c941cb17b39e98a-fdd8-40f0-a674-be6acc5a8c7f', 'name': 'isFinished', 'argument-types': [], 'argument-deserialization-types': [], 'arguments': []}
DEBUG, recieved: {'type': 'primitive', 'value': False}
DEBUG, sending: {'command': 'run-method', 'hash-code': '1c941cb17b39e98a-fdd8-40f0-a674-be6acc5a8c7f', 'name': 'isFinished', 'argument-types': [], 'argument-deserialization-types': [], 'arguments': []}
DEBUG, recieved: {'type': 'primitive', 'value': False}
```
It looks like pycromanager seems to ignore the timeout and continues to poll for completion.

**Comment by henrypinkard** [comment]
closing due to inactivity
