### ISSUE TITLE
Intermittent bug with acquire.

### ISSUE THREAD

**Issue by carlkesselman** [micro-manager/pycro-manager#327]
### Bug report

**Bug summary**
I am getting errors in _acq-hook_start that seem to be intermittent.  They seem to show up after some number of repeated acquisitions.  I'm not quite sure how to narrow this down, but I thought I would start with a bug report and see if there is anything obvious.  I can try to narrow this down if it would be helpful.

My setup is that I've got multiple micromanager instances running, each on a different port started with start_headless.  I am leaving 10 ports open between each instance (e.g. starting at dewfault port, default port +10, default port +20).  I am doing concurrent acquisitions from the micromanager instances, each in its own thread.  Here is the error I get:

`Exception in thread AcquisitionHook:
Exception in thread AcquisitionHook:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner
        self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\threading.py", line 910, in run
self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\CARL\Repos\spim-data\spim-data\lib\site-packages\pycromanager\acquire.py", line 154, in _acq_hook_startup_fn
    self._target(*self._args, **self._kwargs)
  File "C:\Users\CARL\Repos\spim-data\spim-data\lib\site-packages\pycromanager\acquire.py", line 154, in _acq_hook_startup_fn
    push_socket = bridge._connect_push(pull_port)
  File "C:\Users\CARL\Repos\spim-data\spim-data\lib\site-packages\pycromanager\core.py", line 353, in _connect_push`

**Code for reproduction**

```python
# Paste your code here
#
#
```

**Expected outcome**

**Actual outcome**

**Version Info**

  * Operating system:
  * pycromanager version: 
  * MicroManager version:
  * Python version:
  * Python environment (command line, IDE, Jupyter notebook, etc)

**Comment by carlkesselman** [comment]
Ok... did a bit more digging, and its kind of what I suspected.  It looks like each acquisition tries to get a new port for the push and pull socket.  This means it will eventually run into the port that I put the next micromanager instance at.  A short-term fix would be for me to just space them further apart.  However, would it be possible to have acquisitions reuse the push and pull ports across calls for the same micromanager instance?

Carl

**Comment by carlkesselman** [comment]
Ok. Spacing out the ports seems to eliminate the program.

**Comment by henrypinkard** [comment]
So there's just some delay in garbage collection but not its not broken altogether?

**Comment by henrypinkard** [comment]
I've gone through the system and made a lot of fixes and improvements, so I suspect this is now fixed. Feel free to reopen if not
