### ISSUE TITLE
start_headless() raise TimeoutError()

### ISSUE THREAD

**Issue by sfzhang** [micro-manager/pycro-manager#386]
**Bug summary**

I run the following demo code which raises `TimeoutError()`

**Code for reproduction**

```python
# Paste your code here
#
#
mm_app_path = 'C:\\Program Files\\Micro-Manager-2.0'
config_file = 'c:\\Program Files\\Micro-Manager-2.0\\MMConfig_demo.cfg'

start_headless(mm_app_path, config_file, timeout=5000)

with Acquisition(directory='E:/Images', name='img_proc',
                     show_display=False,
                     image_process_fn=img_proc_fn,
                     image_saved_fn=image_saved_fn) as acq:
    events = multi_d_acquisition_events(
        num_time_points=5,
        z_start=0, z_end=6, z_step=0.4
    )
    acq.acquire(events)
```

And the traceback is:
```
Traceback (most recent call last):
  File "C:\Users\sheng\PycharmProjects\test_pycromanager\main.py", line 26, in <module>
    start_headless(mm_app_path, config_file, timeout=5000)
  File "C:\Users\sheng\PycharmProjects\test_pycromanager\myvenv\lib\site-packages\pycromanager\acq_util.py", line 75, in start_headless
    core = Core()
  File "C:\Users\sheng\PycharmProjects\test_pycromanager\myvenv\lib\site-packages\pycromanager\java_classes.py", line 82, in __new__
    bridge = Bridge(port=port, convert_camel_case=convert_camel_case, debug=debug)
  File "C:\Users\sheng\PycharmProjects\test_pycromanager\myvenv\lib\site-packages\pycromanager\bridge.py", line 271, in __init__
    raise TimeoutError(
TimeoutError: Socket timed out after 500 milliseconds. Is Micro-Manager running and is the ZMQ server on 4827 option enabled?

Process finished with exit code 1
```
After reading the source code, it seems that we can not connect to `ZMQ` before  the **java** process has been launched successfully in file **acq_util.py**.
And after I add `time.sleep(1)` after launched **java** process, it works.

**Comment by henrypinkard** [comment]
Yes I believe this was already fixed by : https://github.com/micro-manager/pycro-manager/pull/384

Are you still having problems with the version after that?

**Comment by sfzhang** [comment]
When I try to download code from this repo and get the following error:
```
pip install git+https://github.com/micro-manager/pycro-manager.git
Collecting git+https://github.com/micro-manager/pycro-manager.git
  Cloning https://github.com/micro-manager/pycro-manager.git to f:\temp\sfzhang\pip-req-build-v5y5i4u8
  Running command git clone --filter=blob:none --quiet https://github.com/micro-manager/pycro-manager.git 'F:\TEMP\sfzhang\pip-req-build-v5y5i4u8'
  error: invalid path 'test/C:\Users\henry\Desktop\data/tcz_acq_1/Full resolution/NDTiff.index'
  fatal: unable to checkout working tree
```

**Comment by sfzhang** [comment]
After I run `pip install pycromanager --upgrade`, it works now! Thanks!

**Comment by ianhi** [comment]
This can still be an issue because you actually can't set the timeout used because the `__new__` override doesn't pass args (such as `timeout` through to init) see:

https://github.com/micro-manager/pycro-manager/blob/c2f910a0b8d8ae26aa0962671422b427eae2dfc0/pycromanager/bridge.py#L232

**Comment by henrypinkard** [comment]
Good point https://github.com/micro-manager/pycro-manager/pull/389
