### ISSUE TITLE
Micromanager hangs when acquisition started via pycromanager

### ISSUE THREAD

**Issue by haydenVow** [micro-manager/pycro-manager#397]
I am using pycromanager to multi dimensional acquisitions, however if I try to run an acquisition via pycromanager before running one through micromanager the core hangs with the error:
No images are saved.
```
2022-04-04T15:12:26.396375 tid139967450887936 [IFO,App] EDTHangLogger: Missed heartbeat; waiting to see if we are stuck on a single event
2022-04-04T15:12:27.401636 tid139967450887936 [IFO,App] EDTHangLogger: Event handling has exceeded at least 1003 ms (currently 5504 ms since heartbeat timebase)
                                              [       ] Stack traces follow (note: thread states queried later than stack traces)
                                              [       ] Thread 2 [Reference Handler] WAITING
                                              [       ]   at java.lang.Object.wait(Native Method)
                                              [       ]   at java.lang.Object.wait(Object.java:502)
                                              [       ]   at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
                                              [       ]   at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)
                                              [       ] Thread 3 [Finalizer] WAITING
                                              [       ]   at java.lang.Object.wait(Native Method)
                                              [       ]   at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
                                              [       ]   at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
                                              [       ]   at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)
                                              [       ] Thread 4 [Signal Dispatcher] RUNNABLE
                                              [       ] Thread 11 [RMI TCP Accept-0] RUNNABLE
                                              [       ]   at java.net.PlainSocketImpl.socketAccept(Native Method)
                                              [       ]   at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
                                              [       ]   at java.net.ServerSocket.implAccept(ServerSocket.java:560)
                                              [       ]   at java.net.ServerSocket.accept(ServerSocket.java:528)
                                              [       ]   at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:405)
                                              [       ]   at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:377)
                                              [       ]   at java.lang.Thread.run(Thread.java:748)
                                              [       ] Thread 12 [RMI Reaper] WAITING
                                              [       ]   at java.lang.Object.wait(Native Method)
                                              [       ]   at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
                                              [       ]   at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
                                              [       ]   at sun.rmi.transport.ObjectTable$Reaper.run(ObjectTable.java:351)
                                              [       ]   at java.lang.Thread.run(Thread.java:748)
                                              [       ] Thread 13 [GC Daemon] TIMED_WAITING
                                              [       ]   at java.lang.Object.wait(Native Method)
                                              [       ]   at sun.misc.GC$Daemon.run(GC.java:117)
                                              [       ] Thread 14 [Java2D Disposer] WAITING
                                              [       ]   at java.lang.Object.wait(Native Method)
                                              [       ]   at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
                                              [       ]   at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
                                              [       ]   at sun.java2d.Disposer.run(Disposer.java:148)
                                              [       ]   at java.lang.Thread.run(Thread.java:748)
                                              [       ] Thread 16 [AWT-XAWT] RUNNABLE
                                              [       ]   at sun.awt.X11.XToolkit.waitForEvents(Native Method)
                                              [       ]   at sun.awt.X11.XToolkit.run(XToolkit.java:570)
                                              [       ]   at sun.awt.X11.XToolkit.run(XToolkit.java:534)
                                              [       ]   at java.lang.Thread.run(Thread.java:748)
                                              [       ] Thread 17 [process reaper] TIMED_WAITING
                                              [       ]   at sun.misc.Unsafe.park(Native Method)
                                              [       ]   at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
                                              [       ]   at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
                                              [       ]   at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
                                              [       ]   at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
                                              [       ]   at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073)
                                              [       ]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
                                              [       ]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                                              [       ]   at java.lang.Thread.run(Thread.java:748)
                                              [       ] Thread 18 [AWT-EventQueue-1] BLOCKED
                                              [       ]   at java.awt.Container.dispatchEventImpl(Container.java:2299)
                                              [       ]   at java.awt.Component.dispatchEvent(Component.java:4711)
                                              [       ]   at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
                                              [       ]   at java.awt.EventQueue.access$500(EventQueue.java:97)
                                              [       ]   at java.awt.EventQueue$3.run(EventQueue.java:709)
                                              [       ]   at java.awt.EventQueue$3.run(EventQueue.java:703)
                                              [       ]   at java.security.AccessController.doPrivileged(Native Method)
                                              [       ]   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
                                              [       ]   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
                                              [       ]   at java.awt.EventQueue$4.run(EventQueue.java:733)
                                              [       ]   at java.awt.EventQueue$4.run(EventQueue.java:731)
                                              [       ]   at java.security.AccessController.doPrivileged(Native Method)
                                              [       ]   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
                                              [       ]   at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
                                              [       ]   at org.GNOME.Accessibility.AtkWrapper$6.dispatchEvent(AtkWrapper.java:705)
                                              [       ]   at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
                                              [       ]   at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
                                              [       ]   at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
                                              [       ]   at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
                                              [       ]   at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
                                              [       ]   at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
                                              [       ] Thread 19 [AWT-Shutdown] WAITING
                                              [       ]   at java.lang.Object.wait(Native Method)
                                              [       ]   at java.lang.Object.wait(Object.java:502)
                                              [       ]   at sun.awt.AWTAutoShutdown.run(AWTAutoShutdown.java:295)
                                              [       ]   at java.lang.Thread.run(Thread.java:748)
                                              [       ] Thread 21 [Thread-1] RUNNABLE
                                              [       ] Thread 22 [DestroyJavaVM] RUNNABLE
                                              [       ] Thread 26 [Timer-0] TIMED_WAITING
                                              [       ]   at java.lang.Object.wait(Native Method)
                                              [       ]   at java.util.TimerThread.mainLoop(Timer.java:552)
                                              [       ]   at java.util.TimerThread.run(Timer.java:505)
                                              [       ] Thread 28 [User Profile Saver Pool Thread 0] TIMED_WAITING
                                              [       ]   at sun.misc.Unsafe.park(Native Method)
                                              [       ]   at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
                                              [       ]   at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
                                              [       ]   at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
                                              [       ]   at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
                                              [       ]   at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
                                              [       ]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
                                              [       ]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                                              [       ]   at java.lang.Thread.run(Thread.java:748)
                                              [       ] Thread 29 [TimerQueue] WAITING
                                              [       ]   at sun.misc.Unsafe.park(Native Method)
                                              [       ]   at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
                                              [       ]   at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
                                              [       ]   at java.util.concurrent.DelayQueue.take(DelayQueue.java:211)
                                              [       ]   at javax.swing.TimerQueue.run(TimerQueue.java:174)
                                              [       ]   at java.lang.Thread.run(Thread.java:748)
                                              [       ] Thread 30 [EDTHangLogger timer] RUNNABLE
                                              [       ]   at java.lang.Thread.dumpThreads(Native Method)
                                              [       ]   at java.lang.Thread.getAllStackTraces(Thread.java:1610)
                                              [       ]   at org.micromanager.internal.diagnostics.EDTHangLogger.checkForHang(EDTHangLogger.java:224)
                                              [       ]   at org.micromanager.internal.diagnostics.EDTHangLogger.access$100(EDTHangLogger.java:34)
                                              [       ]   at org.micromanager.internal.diagnostics.EDTHangLogger$2.run(EDTHangLogger.java:211)
                                              [       ]   at java.util.TimerThread.mainLoop(Timer.java:555)
                                              [       ]   at java.util.TimerThread.run(Timer.java:505)
                                              [       ] Thread 31 [Thread-5] TIMED_WAITING
                                              [       ]   at java.lang.Object.wait(Native Method)
                                              [       ]   at bsh.util.JConsole$BlockingPipedInputStream.read(JConsole.java:771)
                                              [       ]   at java.io.PipedInputStream.read(PipedInputStream.java:377)
                                              [       ]   at java.io.InputStream.read(InputStream.java:101)
                                              [       ]   at bsh.util.JConsole.inPipeWatcher(JConsole.java:667)
                                              [       ]   at bsh.util.JConsole.run(JConsole.java:677)
                                              [       ]   at java.lang.Thread.run(Thread.java:748)
                                              [       ] Thread 32 [BeanShell interpreter] TIMED_WAITING
                                              [       ]   at java.lang.Object.wait(Native Method)
                                              [       ]   at java.io.PipedInputStream.read(PipedInputStream.java:326)
                                              [       ]   at java.io.PipedInputStream.read(PipedInputStream.java:377)
                                              [       ]   at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
                                              [       ]   at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
                                              [       ]   at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
                                              [       ]   at java.io.InputStreamReader.read(InputStreamReader.java:184)
                                              [       ]   at bsh.JavaCharStream.FillBuff(JavaCharStream.java:160)
                                              [       ]   at bsh.JavaCharStream.ReadByte(JavaCharStream.java:188)
                                              [       ]   at bsh.JavaCharStream.readChar(JavaCharStream.java:289)
                                              [       ]   at bsh.JavaCharStream.BeginToken(JavaCharStream.java:209)
                                              [       ]   at bsh.ParserTokenManager.getNextToken(ParserTokenManager.java:2072)
                                              [       ]   at bsh.Parser.jj_ntk(Parser.java:6022)
                                              [       ]   at bsh.Parser.Line(Parser.java:163)
                                              [       ]   at bsh.Interpreter.Line(Interpreter.java:1011)
                                              [       ]   at bsh.Interpreter.run(Interpreter.java:462)
                                              [       ]   at java.lang.Thread.run(Thread.java:748)
                                              [       ] Thread 34 [ZMQ Server ] WAITING
                                              [       ]   at sun.misc.Unsafe.park(Native Method)
                                              [       ]   at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
                                              [       ]   at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:429)
                                              [       ]   at java.util.concurrent.FutureTask.get(FutureTask.java:191)
                                              [       ]   at org.GNOME.Accessibility.AtkUtil.invokeInSwing(AtkUtil.java:68)
                                              [       ]   at org.GNOME.Accessibility.AtkObject.hashCode(AtkObject.java:234)
                                              [       ]   at org.GNOME.Accessibility.AtkWrapper.emitSignal(Native Method)
                                              [       ]   at org.GNOME.Accessibility.AtkWrapper$5.propertyChange(AtkWrapper.java:545)
                                              [       ]   at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
                                              [       ]   at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
                                              [       ]   at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
                                              [       ]   at javax.accessibility.AccessibleContext.firePropertyChange(AccessibleContext.java:768)
                                              [       ]   at javax.swing.JLabel.setIcon(JLabel.java:393)
                                              [       ]   at javax.swing.DefaultListCellRenderer.getListCellRendererComponent(DefaultListCellRenderer.java:150)
                                              [       ]   at org.micromanager.display.inspector.internal.panels.intensity.ColorModeCell.getListCellRendererComponent(ColorModeCell.java:81)
                                              [       ]   at javax.swing.plaf.basic.BasicComboBoxUI.getDisplaySize(BasicComboBoxUI.java:1353)
                                              [       ]   at javax.swing.plaf.basic.BasicComboBoxUI.getBaselineResizeBehavior(BasicComboBoxUI.java:1011)
                                              [       ]   at javax.swing.JComponent.getBaselineResizeBehavior(JComponent.java:2592)
                                              [       ]   at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
                                              [       ]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                                              [       ]   at java.lang.reflect.Method.invoke(Method.java:498)
                                              [       ]   at net.miginfocom.swing.SwingComponentWrapper.hasBaseline(Unknown Source)
                                              [       ]   at net.miginfocom.layout.Grid$CompWrap.isBaselineAlign(Unknown Source)
                                              [       ]   at net.miginfocom.layout.Grid$CompWrap.access$3900(Unknown Source)
                                              [       ]   at net.miginfocom.layout.Grid.divideIntoLinkedGroups(Unknown Source)
                                              [       ]   at net.miginfocom.layout.Grid.<init>(Unknown Source)
                                              [       ]   at net.miginfocom.swing.MigLayout.checkCache(Unknown Source)
                                              [       ]   at net.miginfocom.swing.MigLayout.getSizeImpl(Unknown Source)
                                              [       ]   at net.miginfocom.swing.MigLayout.preferredLayoutSize(Unknown Source)
                                              [       ]   at java.awt.Container.preferredSize(Container.java:1799)
                                              [       ]   at java.awt.Container.getPreferredSize(Container.java:1783)
                                              [       ]   at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
                                              [       ]   at net.miginfocom.swing.SwingComponentWrapper.getMinimumWidth(Unknown Source)
                                              [       ]   at net.miginfocom.layout.Grid$CompWrap.getSize(Unknown Source)
                                              [       ]   at net.miginfocom.layout.Grid$CompWrap.<init>(Unknown Source)
                                              [       ]   at net.miginfocom.layout.Grid$CompWrap.<init>(Unknown Source)
                                              [       ]   at net.miginfocom.layout.Grid.<init>(Unknown Source)
                                              [       ]   at net.miginfocom.swing.MigLayout.checkCache(Unknown Source)
                                              [       ]   at net.miginfocom.swing.MigLayout.getSizeImpl(Unknown Source)
                                              [       ]   at net.miginfocom.swing.MigLayout.preferredLayoutSize(Unknown Source)
                                              [       ]   at java.awt.Container.preferredSize(Container.java:1799)
                                              [       ]   at java.awt.Container.getPreferredSize(Container.java:1783)
                                              [       ]   at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
                                              [       ]   at net.miginfocom.swing.SwingComponentWrapper.getPreferredHeight(Unknown Source)
                                              [       ]   at net.miginfocom.layout.Grid$CompWrap.transferBounds(Unknown Source)
                                              [       ]   at net.miginfocom.layout.Grid$CompWrap.access$1800(Unknown Source)
                                              [       ]   at net.miginfocom.layout.Grid.layout(Unknown Source)
                                              [       ]   at net.miginfocom.swing.MigLayout.layoutContainer(Unknown Source)
                                              [       ]   at java.awt.Container.layout(Container.java:1513)
                                              [       ]   at java.awt.Container.doLayout(Container.java:1502)
                                              [       ]   at java.awt.Container.validateTree(Container.java:1698)
                                              [       ]   at java.awt.Container.validateTree(Container.java:1707)
                                              [       ]   at java.awt.Container.validateTree(Container.java:1707)
                                              [       ]   at java.awt.Container.validateTree(Container.java:1707)
                                              [       ]   at java.awt.Container.validateTree(Container.java:1707)
                                              [       ]   at java.awt.Container.validateTree(Container.java:1707)
                                              [       ]   at java.awt.Container.validateTree(Container.java:1707)
                                              [       ]   at java.awt.Container.validateTree(Container.java:1707)
                                              [       ]   at java.awt.Container.validateTree(Container.java:1707)
                                              [       ]   at java.awt.Container.validate(Container.java:1633)
                                              [       ]   at java.awt.Container.validateUnconditionally(Container.java:1670)
                                              [       ]   at java.awt.Window.show(Window.java:1033)
                                              [       ]   at java.awt.Component.show(Component.java:1671)
                                              [       ]   at java.awt.Component.setVisible(Component.java:1623)
                                              [       ]   at java.awt.Window.setVisible(Window.java:1014)
                                              [       ]   at org.micromanager.display.inspector.internal.InspectorController.setVisible(InspectorController.java:257)
                                              [       ]   at org.micromanager.display.internal.DefaultDisplayManager.createInspectorForFrontmostDataViewer(DefaultDisplayManager.java:288)
                                              [       ]   at org.micromanager.display.internal.DefaultDisplayManager.onEvent(DefaultDisplayManager.java:540)
                                              [       ]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                                              [       ]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                                              [       ]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                                              [       ]   at java.lang.reflect.Method.invoke(Method.java:498)
                                              [       ]   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
                                              [       ]   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
                                              [       ]   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
                                              [       ]   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
                                              [       ]   at com.google.common.eventbus.EventBus.post(EventBus.java:275)
                                              [       ]   at org.micromanager.display.internal.DataViewerCollection.onEvent(DataViewerCollection.java:111)
                                              [       ]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                                              [       ]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                                              [       ]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                                              [       ]   at java.lang.reflect.Method.invoke(Method.java:498)
                                              [       ]   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
                                              [       ]   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
                                              [       ]   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
                                              [       ]   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
                                              [       ]   at com.google.common.eventbus.EventBus.post(EventBus.java:275)
                                              [       ]   at org.micromanager.display.AbstractDataViewer.postEvent(AbstractDataViewer.java:98)
                                              [       ]   at org.micromanager.display.internal.displaywindow.DisplayController.setFrameVisible(DisplayController.java:306)
                                              [       ]   at org.micromanager.display.internal.displaywindow.DisplayController.show(DisplayController.java:317)
                                              [       ]   at org.micromanager.display.internal.DefaultDisplayManager.createDisplay(DefaultDisplayManager.java:268)
                                              [       ]   at org.micromanager.acquisition.internal.MMAcquisition.<init>(MMAcquisition.java:178)
                                              [       ]   at org.micromanager.acquisition.internal.AcquisitionWrapperEngine.runAcquisition(AcquisitionWrapperEngine.java:201)
                                              [       ]   at org.micromanager.acquisition.internal.AcquisitionWrapperEngine.acquire(AcquisitionWrapperEngine.java:65)
                                              [       ]   at org.micromanager.internal.dialogs.AcqControlDlg.runAcquisition(AcqControlDlg.java:1564)
                                              [       ]   at org.micromanager.acquisition.internal.DefaultAcquisitionManager.executeAcquisition(DefaultAcquisitionManager.java:111)
                                              [       ]   at org.micromanager.acquisition.internal.DefaultAcquisitionManager.runAcquisition(DefaultAcquisitionManager.java:141)
                                              [       ]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                                              [       ]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                                              [       ]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                                              [       ]   at java.lang.reflect.Method.invoke(Method.java:498)
                                              [       ]   at org.micromanager.internal.zmq.ZMQServer.runMethod(ZMQServer.java:388)
                                              [       ]   at org.micromanager.internal.zmq.ZMQServer.parseAndExecuteCommand(ZMQServer.java:466)
                                              [       ]   at org.micromanager.internal.zmq.ZMQServer.lambda$initialize$2(ZMQServer.java:117)
                                              [       ]   at org.micromanager.internal.zmq.ZMQServer$$Lambda$146/459981212.call(Unknown Source)
                                              [       ]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                              [       ]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                                              [       ]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                                              [       ]   at java.lang.Thread.run(Thread.java:748)
                                              [       ] Thread 35 [reaper-1] RUNNABLE
                                              [       ]   at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
                                              [       ]   at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
                                              [       ]   at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
                                              [       ]   at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
                                              [       ]   at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
                                              [       ]   at zmq.poll.Poller.run(Poller.java:234)
                                              [       ]   at java.lang.Thread.run(Thread.java:748)
                                              [       ] Thread 36 [iothread-2] RUNNABLE
                                              [       ]   at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
                                              [       ]   at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
                                              [       ]   at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
                                              [       ]   at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
                                              [       ]   at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
                                              [       ]   at zmq.poll.Poller.run(Poller.java:234)
                                              [       ]   at java.lang.Thread.run(Thread.java:748)
                                              [       ] Thread 38 [PrioritizedEventBus Pool Thread 0] WAITING
                                              [       ]   at sun.misc.Unsafe.park(Native Method)
                                              [       ]   at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
                                              [       ]   at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
                                              [       ]   at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
                                              [       ]   at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
                                              [       ]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
                                              [       ]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                                              [       ]   at java.lang.Thread.run(Thread.java:748)
                                              [       ] Thread 40 [AbstractDataViewer Pool Pool Thread 0] WAITING
                                              [       ]   at sun.misc.Unsafe.park(Native Method)
                                              [       ]   at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
                                              [       ]   at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
                                              [       ]   at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
                                              [       ]   at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
                                              [       ]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
                                              [       ]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                                              [       ]   at java.lang.Thread.run(Thread.java:748)
```

I have been able to reproduce this a couple of ways. First:

```
from pycromanager import Studio
studio = Studio()
am = studio.get_acquisition_manager()
am.run_acquisition()
```

and also in a similar way using the multi_d_acquisition_event:

```
from pycromanager import Acquisition, multi_d_acquisition_events
events = multi_d_acquisition_events(1)
with Acquisition(directory = "path/to/folder", name="acquisition_name") as acq:
    acq.acquire(events)
```
edit* 
the above code block works, however when I run:
```
from pycromanager import Acquisition, multi_d_acquisition_events
events = multi_d_acquisition_events(xyz_positions = [[some_x, some_y, some_z]])
with Acquisition(directory = "path/to/folder", name="acquisition_name", debug=True) as acq:
    acq.acquire(events)
```
no image is captured, the stage never moves and the core is continually probed for the acquisition finished which doesn't happen unless I manually end it.

If I run an acquisition in micromanager using the gui, and then run the above there are no issues (which I think means its related to the dataStore)

I have a feeling this is related to either [#1282](https://github.com/micro-manager/micro-manager/pull/1282) in micromanager, or something to do with how pycromanager manages the acquisition engine/datastore.

Running on linux ubuntu 20.0
Full log file attached
[corelog.txt](https://github.com/micro-manager/pycro-manager/files/8406965/corelog.txt)

**Comment by henrypinkard** [comment]
> from pycromanager import Acquisition, multi_d_acquisition_events
> events = multi_d_acquisition_events(xyz_positions = [[some_x, some_y, some_z]])
> with Acquisition(directory = "path/to/folder", name="acquisition_name", debug=True) as acq:
>     acq.acquire(events)

Is it related to `debug=True` maybe? Micro-Manager and pycro-manager use entirely seperate acquisition systems, so if youre able to find the same bug that comes up in both it is likely related to your hardware. Does this show up with demo configuration?

**Comment by haydenVow** [comment]
happens with `debug=False` as well, and with the demo config.

**Comment by henrypinkard** [comment]
Works fine for me with demo config, and I think this is a common enough thing that is it were generally broken there would be a lot of complaints. The fact that this happens with both APIs tells me its very likely something low level. Maybe this has to do with your hard drive/saving permissions somehow. Or is your hard drive close to full?

I dont see anything related to pycromanager in your core log message above (maybe this was generated using micromanager).
