### ISSUE TITLE
ZMQException when calling Acquisition() multiple times

### ISSUE THREAD

**Issue by franziskadecker** [micro-manager/pycro-manager#406]
**What I would like to do:**
Run a time lapse where the acquisition parameters (e.g., size and location of the z-stack, channels, what happens to the acquired data) and other hardware settings not controlled via MicroManager change depending on the number of the run. The only way I could come up with for doing that is to run a timing/scheduling function while keeping track of the run number. Depending on the run number, some hardware parameters are changed and Acquisition() is called with run number-specific parameters and events.

**Problem:**
Calling Acquisition() multiple times seems to cause problems that vary a bit run by run but are always ZMQExeptions. The error appears any time between 2min and 5h after starting the code and doesn’t seem to be correlated to the interval of the timing function. Running the same code, I get the following 3 cases of error messages, but I have no idea what determines which of the exceptions is raised:

Error #1:
```
Traceback (most recent call last):
  File "C:\Users\fdecker\Documents\Python\PyCharm_projects\Pycromanager_1_env\opto_timelapse_minimal.py", line 36, in <module>
    schedule.run_pending()
  File "C:\Python\Miniconda3\envs\Pycromanager_1\lib\site-packages\schedule\__init__.py", line 780, in run_pending
    default_scheduler.run_pending()
  File "C:\Python\Miniconda3\envs\Pycromanager_1\lib\site-packages\schedule\__init__.py", line 100, in run_pending
    self._run_job(job)
  File "C:\Python\Miniconda3\envs\Pycromanager_1\lib\site-packages\schedule\__init__.py", line 172, in _run_job
    ret = job.run()
  File "C:\Python\Miniconda3\envs\Pycromanager_1\lib\site-packages\schedule\__init__.py", line 661, in run
    ret = self.job_func()
  File "C:\Users\fdecker\Documents\Python\PyCharm_projects\Pycromanager_1_env\opto_timelapse_minimal.py", line 26, in acquire_stacks_lr
    with Acquisition(directory=save_dir, name=save_name, show_display=False) as acq:
  File "C:\Python\Miniconda3\envs\Pycromanager_1\lib\site-packages\pycromanager\acquisitions.py", line 331, in __init__
    self._create_remote_acquisition(**named_args)
  File "C:\Python\Miniconda3\envs\Pycromanager_1\lib\site-packages\pycromanager\acquisitions.py", line 433, in _create_remote_acquisition
    self._remote_acq = acq_factory.create_acquisition(
  File "C:\Python\Miniconda3\envs\Pycromanager_1\lib\site-packages\pycromanager\bridge.py", line 489, in <lambda>
    ): instance._translate_call(signatures_list, args, static = _java_class == 'java.lang.Class')
  File "C:\Python\Miniconda3\envs\Pycromanager_1\lib\site-packages\pycromanager\bridge.py", line 612, in _translate_call
    recieved = self._socket.receive()
  File "C:\Python\Miniconda3\envs\Pycromanager_1\lib\site-packages\pycromanager\bridge.py", line 175, in receive
    self._check_exception(message)
  File "C:\Python\Miniconda3\envs\Pycromanager_1\lib\site-packages\pycromanager\bridge.py", line 180, in _check_exception
    raise Exception(response["value"])
Exception: org.zeromq.ZMQException: Errno 48 : Address already in use
org.zeromq.ZMQ$Socket.mayRaise(ZMQ.java:3533)
org.zeromq.ZMQ$Socket.bind(ZMQ.java:2987)
org.micromanager.internal.zmq.ZMQPushSocket.initialize(ZMQPushSocket.java:32)
org.micromanager.internal.zmq.ZMQSocketWrapper.<init>(ZMQSocketWrapper.java:41)
org.micromanager.internal.zmq.ZMQSocketWrapper.<init>(ZMQSocketWrapper.java:45)
org.micromanager.internal.zmq.ZMQPushSocket.<init>(ZMQPushSocket.java:24)
org.micromanager.remote.RemoteStorageMonitor.<init>(RemoteStorageMonitor.java:35)
org.micromanager.remote.RemoteViewerStorageAdapter.initialize(RemoteViewerStorageAdapter.java:98)
org.micromanager.acqj.main.Acquisition.initialize(Acquisition.java:268)
org.micromanager.acqj.main.Acquisition.initialize(Acquisition.java:216)
org.micromanager.remote.RemoteAcquisition.<init>(RemoteAcquisition.java:32)
org.micromanager.remote.RemoteAcquisitionFactory.createAcquisition(RemoteAcquisitionFactory.java:53)
sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
org.micromanager.internal.zmq.ZMQServer.runMethod(ZMQServer.java:388)
org.micromanager.internal.zmq.ZMQServer.parseAndExecuteCommand(ZMQServer.java:466)
org.micromanager.internal.zmq.ZMQServer.lambda$initialize$2(ZMQServer.java:117)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)
```

Error #2:
```
Traceback (most recent call last):
  File "C:\Users\fdecker\Documents\Python\PyCharm_projects\Pycromanager_1_env\opto_timelapse_minimal.py", line 36, in <module>
    schedule.run_pending()
  File "C:\Python\Miniconda3\envs\Pycromanager_1\lib\site-packages\schedule\__init__.py", line 780, in run_pending
    default_scheduler.run_pending()
  File "C:\Python\Miniconda3\envs\Pycromanager_1\lib\site-packages\schedule\__init__.py", line 100, in run_pending
    self._run_job(job)
  File "C:\Python\Miniconda3\envs\Pycromanager_1\lib\site-packages\schedule\__init__.py", line 172, in _run_job
    ret = job.run()
  File "C:\Python\Miniconda3\envs\Pycromanager_1\lib\site-packages\schedule\__init__.py", line 661, in run
    ret = self.job_func()
  File "C:\Users\fdecker\Documents\Python\PyCharm_projects\Pycromanager_1_env\opto_timelapse_minimal.py", line 26, in acquire_stacks_lr
    with Acquisition(directory=save_dir, name=save_name, show_display=False) as acq:
  File "C:\Python\Miniconda3\envs\Pycromanager_1\lib\site-packages\pycromanager\acquisitions.py", line 331, in __init__
    self._create_remote_acquisition(**named_args)
  File "C:\Python\Miniconda3\envs\Pycromanager_1\lib\site-packages\pycromanager\acquisitions.py", line 433, in _create_remote_acquisition
    self._remote_acq = acq_factory.create_acquisition(
  File "C:\Python\Miniconda3\envs\Pycromanager_1\lib\site-packages\pycromanager\bridge.py", line 489, in <lambda>
    ): instance._translate_call(signatures_list, args, static = _java_class == 'java.lang.Class')
  File "C:\Python\Miniconda3\envs\Pycromanager_1\lib\site-packages\pycromanager\bridge.py", line 612, in _translate_call
    recieved = self._socket.receive()
  File "C:\Python\Miniconda3\envs\Pycromanager_1\lib\site-packages\pycromanager\bridge.py", line 175, in receive
    self._check_exception(message)
  File "C:\Python\Miniconda3\envs\Pycromanager_1\lib\site-packages\pycromanager\bridge.py", line 180, in _check_exception
    raise Exception(response["value"])
Exception: org.zeromq.ZMQException: Errno 156384819 : errno 156384819
zmq.Ctx.createSocket(Ctx.java:398)
org.zeromq.ZMQ$Socket.<init>(ZMQ.java:833)
org.zeromq.ZMQ$Socket.<init>(ZMQ.java:819)
org.zeromq.ZMQ$Context.socket(ZMQ.java:652)
org.zeromq.ZContext.createSocket(ZContext.java:131)
org.micromanager.internal.zmq.ZMQPullSocket.initialize(ZMQPullSocket.java:30)
org.micromanager.internal.zmq.ZMQSocketWrapper.<init>(ZMQSocketWrapper.java:41)
org.micromanager.internal.zmq.ZMQSocketWrapper.<init>(ZMQSocketWrapper.java:45)
org.micromanager.internal.zmq.ZMQPullSocket.<init>(ZMQPullSocket.java:24)
org.micromanager.remote.RemoteEventSource.<init>(RemoteEventSource.java:36)
org.micromanager.remote.RemoteAcquisitionFactory.createAcquisition(RemoteAcquisitionFactory.java:45)
sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
org.micromanager.internal.zmq.ZMQServer.runMethod(ZMQServer.java:388)
org.micromanager.internal.zmq.ZMQServer.parseAndExecuteCommand(ZMQServer.java:466)
org.micromanager.internal.zmq.ZMQServer.lambda$initialize$2(ZMQServer.java:117)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)
```

Error #3:
No error message but also no upcoming acquisitions are run. Seems like it gets stuck while trying to save the data from the previous run, but I’m not sure what/where the problem is.

**Minimal example**
Here is a minimal example code that can be run with the MMConfig_demo.cfg and in most cases reproduces the “Exception: org.zeromq.ZMQException: Errno 48 : Address already in use” (but according to the debugging info, sockets have been closed properly). Sometimes it will also raise “Exception: org.zeromq.ZMQException: Errno 156384819 : errno 156384819” and sometimes it will just get stuck and not continue with the upcoming acquisitions and not raise any errors.

```python
from pycromanager import Core, Acquisition, multi_d_acquisition_events 
import schedule 
import time   

save_dir = 'D:\\220420' 
save_name = 'test' 
time_interval_sec = 15

  events = multi_d_acquisition_events(z_start=0, z_end=10, z_step=1, channel_group='Channel', channels=['DAPI'])  

mmcore = Core()   


def acquire_stacks():     
    with Acquisition(directory=save_dir, name=save_name, show_display=False, debug=True) as acq: 
        acq.acquire(events)

      print('run done')   

# schedule acquisition events and run them 
schedule.every(time_interval_sec).seconds.do(acquire_stacks)  

while True: 
    schedule.run_pending()
     time.sleep(1)
```

Output from debugging mode and error message (the first part until “run done” gets repeated n times before the error appears, where n can vary a lot from 10 to a few hundred):

```
connecting 4827
DEBUG, sending: {'command': 'connect', 'debug': True}
DEBUG, recieved: {'type': 'none', 'version': '4.2.0'}
binding 4828
got event(s): [{'axes': {'z': 0}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 0}, {'axes': {'z': 1}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 1}, {'axes': {'z': 2}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 2}, {'axes': {'z': 3}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 3}, {'axes': {'z': 4}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 4}, {'axes': {'z': 5}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 5}, {'axes': {'z': 6}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 6}, {'axes': {'z': 7}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 7}, {'axes': {'z': 8}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 8}, {'axes': {'z': 9}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 9}, {'axes': {'z': 10}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 10}]
DEBUG, sending: {'events': [{'axes': {'z': 0}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 0}, {'axes': {'z': 1}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 1}, {'axes': {'z': 2}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 2}, {'axes': {'z': 3}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 3}, {'axes': {'z': 4}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 4}, {'axes': {'z': 5}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 5}, {'axes': {'z': 6}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 6}, {'axes': {'z': 7}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 7}, {'axes': {'z': 8}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 8}, {'axes': {'z': 9}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 9}, {'axes': {'z': 10}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 10}]}
sent events
got event(s): None
DEBUG, sending: {'events': [{'special': 'acquisition-end'}]}
closed socket 4828
closed socket 4827
run done
Traceback (most recent call last):
  File "C:\Users\fdecker\Documents\Python\PyCharm_projects\Pycromanager_1_env\opto_timelapse_minimal.py", line 36, in <module>
    schedule.run_pending()
  File "C:\Python\Miniconda3\envs\Pycromanager_1\lib\site-packages\schedule\__init__.py", line 780, in run_pending
    default_scheduler.run_pending()
  File "C:\Python\Miniconda3\envs\Pycromanager_1\lib\site-packages\schedule\__init__.py", line 100, in run_pending
    self._run_job(job)
  File "C:\Python\Miniconda3\envs\Pycromanager_1\lib\site-packages\schedule\__init__.py", line 172, in _run_job
    ret = job.run()
  File "C:\Python\Miniconda3\envs\Pycromanager_1\lib\site-packages\schedule\__init__.py", line 661, in run
    ret = self.job_func()
  File "C:\Users\fdecker\Documents\Python\PyCharm_projects\Pycromanager_1_env\opto_timelapse_minimal.py", line 26, in acquire_stacks_lr
    with Acquisition(directory=save_dir, name=save_name, show_display=False, debug=True) as acq:
  File "C:\Python\Miniconda3\envs\Pycromanager_1\lib\site-packages\pycromanager\acquisitions.py", line 331, in __init__
    self._create_remote_acquisition(**named_args)
  File "C:\Python\Miniconda3\envs\Pycromanager_1\lib\site-packages\pycromanager\acquisitions.py", line 433, in _create_remote_acquisition
    self._remote_acq = acq_factory.create_acquisition(
  File "C:\Python\Miniconda3\envs\Pycromanager_1\lib\site-packages\pycromanager\bridge.py", line 489, in <lambda>
    ): instance._translate_call(signatures_list, args, static = _java_class == 'java.lang.Class')
  File "C:\Python\Miniconda3\envs\Pycromanager_1\lib\site-packages\pycromanager\bridge.py", line 612, in _translate_call
    recieved = self._socket.receive()
  File "C:\Python\Miniconda3\envs\Pycromanager_1\lib\site-packages\pycromanager\bridge.py", line 175, in receive
    self._check_exception(message)
  File "C:\Python\Miniconda3\envs\Pycromanager_1\lib\site-packages\pycromanager\bridge.py", line 180, in _check_exception
    raise Exception(response["value"])
Exception: org.zeromq.ZMQException: Errno 48 : Address already in use
org.zeromq.ZMQ$Socket.mayRaise(ZMQ.java:3533)
org.zeromq.ZMQ$Socket.bind(ZMQ.java:2987)
org.micromanager.internal.zmq.ZMQPushSocket.initialize(ZMQPushSocket.java:32)
org.micromanager.internal.zmq.ZMQSocketWrapper.<init>(ZMQSocketWrapper.java:41)
org.micromanager.internal.zmq.ZMQSocketWrapper.<init>(ZMQSocketWrapper.java:45)
org.micromanager.internal.zmq.ZMQPushSocket.<init>(ZMQPushSocket.java:24)
org.micromanager.remote.RemoteStorageMonitor.<init>(RemoteStorageMonitor.java:35)
org.micromanager.remote.RemoteViewerStorageAdapter.initialize(RemoteViewerStorageAdapter.java:98)
org.micromanager.acqj.main.Acquisition.initialize(Acquisition.java:268)
org.micromanager.acqj.main.Acquisition.initialize(Acquisition.java:216)
org.micromanager.remote.RemoteAcquisition.<init>(RemoteAcquisition.java:32)
org.micromanager.remote.RemoteAcquisitionFactory.createAcquisition(RemoteAcquisitionFactory.java:53)
sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
org.micromanager.internal.zmq.ZMQServer.runMethod(ZMQServer.java:388)
org.micromanager.internal.zmq.ZMQServer.parseAndExecuteCommand(ZMQServer.java:466)
org.micromanager.internal.zmq.ZMQServer.lambda$initialize$2(ZMQServer.java:117)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)
```

**Version info:**
- Operating system: Windows 10
- pycromanager: 0.17.4
- MicroManager: 2.0.1 nightly build 22/03/30
- Python: 3.9.7
- code run in PyCharm 2021.3.1 (Community Edition)

**Comment by henrypinkard** [comment]
Thanks for this detailed testing and report. Clearly, there's some timing problem with the ZMQ sockets created by acquisitions. Since this occurs with the call `self._remote_acq = acq_factory.create_acquisition`, it seems to me that this problem is arising on the Java side, likely from the socket that gets spun up to start receiving acquisition events from python. There might be an error happening on the Java side, which would be recorded in the micromanager core log that could be useful to understanding this better. 

Also, I wonder whether this has to do with multiple calls to Acquisition colliding, or simply occurs when running an acquisition with some low probability. This could be tested by running multiple acquisitions by repeatedly running independent python processes/scripts from the command line. Knowing this would be very informative because it would determine whether this is a problem with acquisition shutdown or multiple acquisitions running.

You might be able to just work around this by adding in a new dimension into the `axes` of your acquisition events that increments the acquisition number. You don't need to have the same channels/settings for every increment of this

**Comment by henrypinkard** [comment]
possibly same as #286

**Comment by franziskadecker** [comment]
Thanks for your quick reply, thoughts and suggestions. I attached the micromanager core log file from one of the runs where the "Exception: org.zeromq.ZMQException: Errno 48 : Address already in use" came up. 
[CoreLog20220425T154100_pid12224.txt](https://github.com/micro-manager/pycro-manager/files/8561848/CoreLog20220425T154100_pid12224.txt)

I will also check what happens when I repeatedly run python scripts containing Acquisition() from the command line.

Could you please elaborate a bit further on your last suggestion with the additional dimension in axes? Would this be pre-defining all acquisition events? And how would I combine this with different non-micromanager controlled hardware settings for each acquistion?

**Comment by franziskadecker** [comment]
I ran the following python script every few seconds from the command line:

```python
from pycromanager import Core, Acquisition, multi_d_acquisition_events
 import time  

save_dir = 'D:\\220426' 
save_name = 'test'   

events = multi_d_acquisition_events(z_start=0, z_end=10, z_step=1, channel_group='Channel', channels=['DAPI'])

  mmcore = Core()   

with Acquisition(directory=save_dir, name=save_name, show_display=False, debug=True) as acq: 
    acq.acquire(events)  

time.sleep(2) 
print('run done') 
```

After ~10min it changed from the sockets 4827 and 4828 to using 5041 and 4827. Then after ~1h it started raising the following exception every time the python script was called:
```
Exception: org.zeromq.ZMQException: Errno 156384819 : errno 156384819
```

Here is the output of the last functional run and the first 2 times of the error message:
[error_command_line_run.txt](https://github.com/micro-manager/pycro-manager/files/8564264/error_command_line_run.txt)

**Comment by henrypinkard** [comment]
> After ~10min it changed from the sockets 4827 and 4828 to using 5041 and 4827. Then after ~1h it started raising the following exception every time the python script was called:

Okay thanks for checking! Looks like this is then an issue with the allocation of port numbers in the first place. I can look into that a bit

**Comment by henrypinkard** [comment]
https://github.com/micro-manager/pycro-manager/pull/407 fixes the failure to close ports with each acquisition run. Not sure if this is the entirety of the problem, but definitely solves part of it. Upgrade the pip version to 0.17.6 to use it.

I'm curious to know what, if any issues remain after this.

**Comment by franziskadecker** [comment]
I ran the minimal example with version 0.17.6 and unfortunately got the same error after ~1h: 
Exception: org.zeromq.ZMQException: Errno 48 : Address already in use
```
Traceback (most recent call last):
  File "C:\Users\fdecker\Documents\Python\PyCharm_projects\Pycromanager_2_env\opto_timelapse_minimal.py", line 36, in <module>
    schedule.run_pending()
  File "C:\Python\Miniconda3\envs\Pycromanager_2\lib\site-packages\schedule\__init__.py", line 780, in run_pending
    default_scheduler.run_pending()
  File "C:\Python\Miniconda3\envs\Pycromanager_2\lib\site-packages\schedule\__init__.py", line 100, in run_pending
    self._run_job(job)
  File "C:\Python\Miniconda3\envs\Pycromanager_2\lib\site-packages\schedule\__init__.py", line 172, in _run_job
    ret = job.run()
  File "C:\Python\Miniconda3\envs\Pycromanager_2\lib\site-packages\schedule\__init__.py", line 661, in run
    ret = self.job_func()
  File "C:\Users\fdecker\Documents\Python\PyCharm_projects\Pycromanager_2_env\opto_timelapse_minimal.py", line 26, in acquire_stacks_lr
    with Acquisition(directory=save_dir, name=save_name, show_display=False, debug=True) as acq:
  File "C:\Python\Miniconda3\envs\Pycromanager_2\lib\site-packages\pycromanager\acquisitions.py", line 331, in __init__
    self._create_remote_acquisition(**named_args)
  File "C:\Python\Miniconda3\envs\Pycromanager_2\lib\site-packages\pycromanager\acquisitions.py", line 433, in _create_remote_acquisition
    self._remote_acq = acq_factory.create_acquisition(
  File "C:\Python\Miniconda3\envs\Pycromanager_2\lib\site-packages\pycromanager\bridge.py", line 489, in <lambda>
    ): instance._translate_call(signatures_list, args, static = _java_class == 'java.lang.Class')
  File "C:\Python\Miniconda3\envs\Pycromanager_2\lib\site-packages\pycromanager\bridge.py", line 612, in _translate_call
    recieved = self._socket.receive()
  File "C:\Python\Miniconda3\envs\Pycromanager_2\lib\site-packages\pycromanager\bridge.py", line 175, in receive
    self._check_exception(message)
  File "C:\Python\Miniconda3\envs\Pycromanager_2\lib\site-packages\pycromanager\bridge.py", line 180, in _check_exception
    raise Exception(response["value"])
Exception: org.zeromq.ZMQException: Errno 48 : Address already in use
org.zeromq.ZMQ$Socket.mayRaise(ZMQ.java:3533)
org.zeromq.ZMQ$Socket.bind(ZMQ.java:2987)
org.micromanager.internal.zmq.ZMQPushSocket.initialize(ZMQPushSocket.java:32)
org.micromanager.internal.zmq.ZMQSocketWrapper.<init>(ZMQSocketWrapper.java:41)
org.micromanager.internal.zmq.ZMQSocketWrapper.<init>(ZMQSocketWrapper.java:45)
org.micromanager.internal.zmq.ZMQPushSocket.<init>(ZMQPushSocket.java:24)
org.micromanager.remote.RemoteStorageMonitor.<init>(RemoteStorageMonitor.java:35)
org.micromanager.remote.RemoteViewerStorageAdapter.initialize(RemoteViewerStorageAdapter.java:98)
org.micromanager.acqj.main.Acquisition.initialize(Acquisition.java:268)
org.micromanager.acqj.main.Acquisition.initialize(Acquisition.java:216)
org.micromanager.remote.RemoteAcquisition.<init>(RemoteAcquisition.java:32)
org.micromanager.remote.RemoteAcquisitionFactory.createAcquisition(RemoteAcquisitionFactory.java:53)
sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
org.micromanager.internal.zmq.ZMQServer.runMethod(ZMQServer.java:388)
org.micromanager.internal.zmq.ZMQServer.parseAndExecuteCommand(ZMQServer.java:466)
org.micromanager.internal.zmq.ZMQServer.lambda$initialize$2(ZMQServer.java:117)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)
```
Here is the Micromanager core log:
[CoreLog20220427T172642_pid9228.txt](https://github.com/micro-manager/pycro-manager/files/8581145/CoreLog20220427T172642_pid9228.txt)

**Comment by henrypinkard** [comment]
Okay, I made several upgrades to try to make this more robust https://github.com/micro-manager/pycro-manager/pull/409.

can you trying pip upgrading and getting tomorrows nightly build and see if that solves the problem?

**Comment by franziskadecker** [comment]
On Friday I upgraded to version 0.17.8 and the nightly build 20220428 and ran the minimal example again. The first run stopped after 12 min without giving an error message (error #3 in my initial post). The debugging info says that it closed the two opened sockets but then it gets stuck while saving the data. There is only the index file but no actual tiff file being saved and no new run is started. Then I closed and restarted everything and ran the exact same code again and it kept running for ~ 12 h until it stalled again without any error message. Here are the debugging log files and core log files:
12min run:
[log_1.txt](https://github.com/micro-manager/pycro-manager/files/8603029/log_1.txt)
[CoreLog20220429T105724_pid7796.txt](https://github.com/micro-manager/pycro-manager/files/8603031/CoreLog20220429T105724_pid7796.txt)

**Comment by henrypinkard** [comment]
So it sounds like it is the same error in both of those cases, is that right? That's at least progress that we've gotten multiple errors down to one :). Did you see an index file but no image data in both cases?

Unfortunately, there doesn't seem to be anything in those logs. I can add some more debug logging in to try to trace this down better.

> The debugging info says that it closed the two opened sockets but then it gets stuck while saving the data. There is only the index file but no actual tiff file being saved and no new run is started.

Is the acquisition on which it says the sockets closed the same as the one with no tiff file, or is the one with no tiff hang and not have its sockets closed?

**Comment by franziskadecker** [comment]
Yes, as far as I can tell, it's the same error in both cases. Another positive thing is that the 12h run was the longest so far :)
In both cases there was only an empty index file, but no image data. The stalling happens after both opened sockets have been closed, which btw were always the same 4827 and 4828 (so no switching to other sockets during the entire time, which I guess means that they have been closed quickly enough before the next run tried to open new sockets). Basically the only thing missing to finish the run seems to be saving the image data and saving information to the index file. I still have no idea what the problem could be because everything looks normal when it stalls (python is still running, no error messages or other complaints, no memory issues, etc.) but it's just not continuing.

**Comment by henrypinkard** [comment]
> Basically the only thing missing to finish the run seems to be saving the image data and saving information to the index file. I still have no idea what the problem could be because everything looks normal when it stalls (python is still running, no error messages or other complaints, no memory issues, etc.) but it's just not continuing.

The way its supposed to work is that data is saved as you go. So its either that its never getting the acquisition events to start acquiring, or something is going wrong when trying to execute those events. Most likely, there is in exception in some internal code that is being suppressed when it shouldn't, and causing everything to mess up. So to try to figure this out, I will exhaustively add a bunch of debug logging at intermediate places. But before doing that I want to see if we can narrow it down any more. 

Specifically, I want to understand if the last sockets to close correspond to the acquisition with no image data, or if the one with no image data is hanging in a suspended state wait to close. Are you able to tell?

**Comment by franziskadecker** [comment]
The debugging information from the run where it gets stuck without saving image data is the following:
```
connecting 4827
DEBUG, sending: {'command': 'connect', 'debug': True}
DEBUG, recieved: {'type': 'none', 'version': '4.2.0'}
binding 4828
got event(s): [{'axes': {'z': 0}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 0}, {'axes': {'z': 1}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 1}, {'axes': {'z': 2}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 2}, {'axes': {'z': 3}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 3}, {'axes': {'z': 4}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 4}, {'axes': {'z': 5}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 5}, {'axes': {'z': 6}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 6}, {'axes': {'z': 7}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 7}, {'axes': {'z': 8}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 8}, {'axes': {'z': 9}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 9}, {'axes': {'z': 10}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 10}]
DEBUG, sending: {'events': [{'axes': {'z': 0}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 0}, {'axes': {'z': 1}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 1}, {'axes': {'z': 2}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 2}, {'axes': {'z': 3}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 3}, {'axes': {'z': 4}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 4}, {'axes': {'z': 5}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 5}, {'axes': {'z': 6}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 6}, {'axes': {'z': 7}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 7}, {'axes': {'z': 8}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 8}, {'axes': {'z': 9}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 9}, {'axes': {'z': 10}, 'channel': {'group': 'Channel', 'config': 'DAPI'}, 'z': 10}]}
sent events
got event(s): None
DEBUG, sending: {'events': [{'special': 'acquisition-end'}]}
closed socket 4828
closed socket 4827
```
Assuming that "closed socket" only gets printed when the sockets actually have been closed, it doesn't look like it's hanging in an opened state. Let me know if you need any other information.

**Comment by henrypinkard** [comment]
Okay so this seems to me like it doesn't have to do with sockets anymore, since they seem to be sending data and closing fine. I added in a bunch of logging to the acquisition engine, which will show up in the core log (itll probably be really big now, so you may have to email it to me). If you download tonight's nightly build it will contain the changes. Make sure you have `Acquisition(core_log_debug=True`.

Also, I noticed some strange behavior with the `schedule` library on my system. Probably good to rule out that it isn't causing the issue by running successive acquisitions from a simple for loop

**Comment by franziskadecker** [comment]
I ran the code again with the nightly build 20220504. This time it stalled after ~ 4h. Here is the core log file:
[CoreLog20220505T140513_pid8672.txt](https://github.com/micro-manager/pycro-manager/files/8632796/CoreLog20220505T140513_pid8672.txt)

I just started running acquisitions from a for loop and will let you know tomorrow whether the code also stalls.

**Comment by henrypinkard** [comment]
Okay, starting to see the problem here. As you suspected, it seems to be stalling on image saving. I added some more logging into the new nightly build so that we can narrow this down further. I have a suspicion as to where this was coming from--a code block on the java side that notifies the python side once data is saved so it can be opened directly there. I wrapped that in a block so that it now won't crash the whole thing if that happens. So you may not see it stall now. But `Image written listener exception` will appear in the core log instead. Even if the stalling is fixed, it would be nice to get to the bottom of what was causing this in the first place because it could still affect other things

**Comment by franziskadecker** [comment]
Here is an info regarding running Acquisition() from a simple for loop:
It’s been running for 24h now (still with the nightly build 20220504) and doesn’t seem to stall or give other errors (so far). So you might be right that the `schedule` library also causes some issues. I'll keep it running over the weekend and let you know what happens.

Next week I can also continue testing things to figure out what exactly causes the stalling and test the new nightly build.

**Comment by franziskadecker** [comment]
Here are some updates:

1) Running Acquisition() from simple for loop:
I manually stopped the run today after almost 4 days of running continuously without stalling or any error messages (nightly build 20220504). So this seems to be working nicely :)

2) I ran the minimal code again (that includes the `schedule` library) with the nightly build 20220505 to see whether it still stalls and/or your new core log message shows up:
It stalled after <1h and I don’t think `Image listener exception` appears in the core log.
[CoreLog20220509T114525_pid12036.txt](https://github.com/micro-manager/pycro-manager/files/8651792/CoreLog20220509T114525_pid12036.txt)
But given that running it with a for loop seems to work and not cause any stalling, it might really be only a problem of the `schedule` library now.

Let me know if there is anything else you would like me to test. Otherwise I’m happy with the fixed ZMQExceptions and using simple for loops instead of the `schedule` library.

**Comment by henrypinkard** [comment]
Great! Maybe the schedule library is somehow starting one acquisition before the previous one finishes or something like that. But if it works, I'm satisfied unless something else comes up. Thanks for all the testing--we managed to make a lot of good improvements!

**Comment by franziskadecker** [comment]
Thanks a lot for your help!
