### ISSUE TITLE
Pycromanager setup on Windows 11

### ISSUE THREAD

**Issue by amoghpj** [micro-manager/pycro-manager#414]
Hi. Apologies if this question is not appropriate for github Issues.

I am trying to setup pycromanager on a Windows 11 machine, but so far pycromanager fails with the same error.

Versions:
Python 3.10
Micro-manager 2.0
Pycromanager 0.17.9.

Note: Micromanager-2.0 works fine, and I have used the GUI successfully.

Details:
I have also installed pymmcore and pymmcore-plus. I have enabled the server at port 4827.
Running the following MWE pops up the GUI window, but fails to acquire anything.

MWE:
```
from pycromanager import Core, Acquisition, multi_d_acquisition_events
import sys
sys.path.append("C:\\Program Files\\Micro-Manager-2.0/")

core = Core()
print(core)

with Acquisition(directory='./', name="hello") as acq:
    events = multi_d_acquisition_events(
        num_time_points=4, time_interval_s=0,
        channel_group='Channel', channels=["CFP"],
        order='tcz')
    print(events)
    acq.acquire(events)
```
 The `hello` folder is created, which contains 
```
hello
├── Full resolution
│   └── NDTiff.index
└── display_settings.txt

1 directory, 2 files
```

Traceback:
```
<pycromanager.bridge.mmcorej_CMMCore object at 0x00000196E95832E0>
[{'axes': {'time': 0}, 'channel': {'group': 'Channel', 'config': 'CFP'}}, {'axes': {'time': 1}, 'channel': {'group': 'Channel', 'config': 'CFP'}}, {'axes': {'time': 2}, 'channel': {'group': 'Channel', 'config': 'CFP'}}, {'axes': {'time': 3}, 'channel': {'group': 'Channel', 'config': 'CFP'}}]
Traceback (most recent call last):
  File "C:\Users\Amogh\Desktop\pycromanager-scripts\mwe.py", line 10, in <module>
    with Acquisition(directory='./', name="hello") as acq:
  File "C:\Users\Amogh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycromanager\acquisitions.py", line 371, in __exit__
    self.await_completion()
  File "C:\Users\Amogh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycromanager\acquisitions.py", line 474, in await_completion
    self._remote_acq.check_for_exceptions()
AttributeError: 'org_micromanager_remote_RemoteAcquisition' object has no attribute 'check_for_exceptions'
Exception ignored in: <function _JavaObjectShadow.__del__ at 0x00000196E7700310>
Traceback (most recent call last):
  File "C:\Users\Amogh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycromanager\bridge.py", line 562, in __del__
  File "C:\Users\Amogh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycromanager\bridge.py", line 552, in _close
  File "C:\Users\Amogh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pycromanager\bridge.py", line 114, in send
AttributeError: 'NoneType' object has no attribute 'send_multipart'
```

I am new to both Windows and hardware interfaces, and I am not sure what the best place to start debugging this would be.
Let me know if I have missed a step in the setup. I am happy to provide more information.

**Comment by henrypinkard** [comment]
Update to the latest nightly build of micromanager
