### ISSUE TITLE
ZMQError when calling image_process_fn repeatedly

### ISSUE THREAD

**Issue by franziskadecker** [micro-manager/pycro-manager#418]
**What I would like to do:**
Run a time-lapse where the majority of the stacks should not be saved. To do this, I followed the example given in the documentation for image processors.

**Problem:**
After some iterations, the code stalls and the following error is raised:

```
Exception in thread ImageProcessor:
Traceback (most recent call last):
  File "C:\Python\Miniconda3\envs\Pycromanager_3\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Python\Miniconda3\envs\Pycromanager_3\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python\Miniconda3\envs\Pycromanager_3\lib\site-packages\pycromanager\acquisitions.py", line 136, in _run_image_processor
    push_socket = bridge._connect_push(pull_port)
  File "C:\Python\Miniconda3\envs\Pycromanager_3\lib\site-packages\pycromanager\bridge.py", line 397, in _connect_push
    return DataSocket(
  File "C:\Python\Miniconda3\envs\Pycromanager_3\lib\site-packages\pycromanager\bridge.py", line 34, in __init__
    self._socket.bind("tcp://{}:{}".format(ip_address, port))
  File "C:\Python\Miniconda3\envs\Pycromanager_3\lib\site-packages\zmq\sugar\socket.py", line 214, in bind
    super().bind(addr)
  File "zmq\backend\cython\socket.pyx", line 540, in zmq.backend.cython.socket.Socket.bind
  File "zmq\backend\cython\checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Permission denied
```

**Minimal example:**
Reproduces the error after n iterations (usually a little more than 100) and uses the MMConfig_demo.cfg.

```python
from pycromanager import Acquisition, multi_d_acquisition_events 
import time  

events = multi_d_acquisition_events(z_start=0, z_end=10, z_step=1, channel_group='Channel', channels=['DAPI'])   


def get_time(): 
    t = time.localtime()
     current_time = time.strftime("%H:%M:%S", t) 
    return current_time   


def img_process_fn(image, metadata): 
    # do nothing to not save the image
     pass   


def opto_stack(): 
    with Acquisition(image_process_fn=img_process_fn, debug=True, core_log_debug=True) as acq: 
        acq.acquire(events)

      print('run done at', get_time())   


for i in range(100000): 
    print('start run ' + str(i) + ' at', get_time())
     opto_stack()
     time.sleep(5)
```

**Log files:**
[CoreLog20220614T144450_pid8228.txt](https://github.com/micro-manager/pycro-manager/files/8899952/CoreLog20220614T144450_pid8228.txt)

The standard debugging log file is too big to upload it here, but if needed, I can send it to you via email.
Here is the end of the file (the last run where stalls):
[end_of_debug_log.txt](https://github.com/micro-manager/pycro-manager/files/8900057/end_of_debug_log.txt)

**Version info:**
- Operating system: Windows 10
- pycromanager: 0.17.10
- MicroManager: 2.0.1 nightly build 22/06/13
- Python: 3.9.7
- code run in PyCharm 2021.3.1 (Community Edition)

**Comment by henrypinkard** [comment]
I see that it counted up to socket 5040 from 4827, so looks like this is another instance of the socket failing to close. I'll look into it

**Comment by henrypinkard** [comment]
Fixed. https://github.com/micro-manager/pycro-manager/pull/419

Update the nightly build tomorrow and pypi version

Thanks for all the stress testing!

**Comment by franziskadecker** [comment]
Thanks for the quick fix!
