### ISSUE TITLE
exception in headless mode

### ISSUE THREAD

**Issue by Heerpa** [micro-manager/pycro-manager#438]
I am starting to used pycromanager for python-controlled image acquisition, and I am following https://pycro-manager.readthedocs.io/en/latest/headless_mode.html. 

pycromanager version is 0.18.3
Micromanager version is 2.0.1 20220401
python is 3.8
The OS is Windows 10 Pro for Workstations

The image data is saved, but I get an exception during the call to acquisition:

```
    from pycromanager import Acquisition, multi_d_acquisition_events, start_headless

    start_headless(mm_app_path, config_file, timeout=5000)

    print('started headless')

    acq_name = r'test_acquisition'

    with Acquisition(directory=save_dir, name=acq_name, show_display=False,
                     ) as acq:
        print('creating events')
        events = multi_d_acquisition_events(num_time_points=n_frames)
        print('printing events')
        for e in events:
            print(e)
        print('acquiring')
        acq.acquire(events)
```

The exception is 
```
started headless
creating events
printing events
{'axes': {'time': 0}}
{'axes': {'time': 1}}
{'axes': {'time': 2}}
{'axes': {'time': 3}}
{'axes': {'time': 4}}
{'axes': {'time': 5}}
{'axes': {'time': 6}}
{'axes': {'time': 7}}
{'axes': {'time': 8}}
{'axes': {'time': 9}}
acquiring
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\PycroFlow\FlowAcquisition.py", line 52, in test_acq2
    acq.acquire(events)
  File "...\anaconda3\envs\pycroflow\lib\site-packages\pycromanager\acquisitions.py", line 376, in __exit__
    self.await_completion()
  File "...\anaconda3\envs\pycroflow\lib\site-packages\pycromanager\acquisitions.py", line 479, in await_completion
    self._remote_acq.check_for_exceptions()
AttributeError: 'org_micromanager_remote_RemoteAcquisition' object has no attribute 'check_for_exceptions'
```
This is a minimal acquisition events example, I also tried specifying more dimensions.

I saw that _remote_acq is a Java object, so I have a hard time checking for check_for_exceptions. Google doesn't show any mentions.

**Comment by henrypinkard** [comment]
Upgrade to the latest nightly build of micro-manager

**Comment by Heerpa** [comment]
Thanks, that solved it!

Can I create two acquisitions sequentially? Apparently, something is not completely closed after the with statement:

```
    with Acquisition(directory=save_dir, name=acq_name, show_display=False,
                     ) as acq:
        print('creating events')
        events = multi_d_acquisition_events(num_time_points=n_frames)
        print('printing events')
        for e in events:
            print(e)
        print('acquiring')
        acq.acquire(events)

    print('second run')

    acq_name = r'test_acquisition2'

    with Acquisition(directory=save_dir, name=acq_name, show_display=False,
                     ) as acq:
        print('creating events')
        events = multi_d_acquisition_events(num_time_points=n_frames)
        print('printing events')
        for e in events:
            print(e)
        print('acquiring')
        acq.acquire(events)
```


Throws:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\FlowAcquisition.py", line 56, in test_acq2
    with Acquisition(directory=save_dir, name=acq_name, show_display=False,
  File "...\anaconda3\envs\pycroflow\lib\site-packages\pycromanager\acquisitions.py", line 332, in __init__
    self._create_remote_acquisition(**named_args)
  File "...\anaconda3\envs\pycroflow\lib\site-packages\pycromanager\acquisitions.py", line 445, in _create_remote_acquisition
    self._remote_acq = acq_factory.create_acquisition(
  File "...\anaconda3\envs\pycroflow\lib\site-packages\pycromanager\bridge.py", line 489, in <lambda>
    ): instance._translate_call(signatures_list, args, static = _java_class == 'java.lang.Class')
  File "...\anaconda3\envs\pycroflow\lib\site-packages\pycromanager\bridge.py", line 612, in _translate_call
    recieved = self._socket.receive()
  File "...\anaconda3\envs\pycroflow\lib\site-packages\pycromanager\bridge.py", line 175, in receive
    self._check_exception(message)
  File "...\anaconda3\envs\pycroflow\lib\site-packages\pycromanager\bridge.py", line 180, in _check_exception
    raise Exception(response["value"])
Exception: org.zeromq.ZMQException: Errno 48 : Address already in use
org.zeromq.ZMQ$Socket.mayRaise(ZMQ.java:3533)
org.zeromq.ZMQ$Socket.bind(ZMQ.java:2987)
org.micromanager.internal.zmq.ZMQPushSocket.initialize(ZMQPushSocket.java:32)
org.micromanager.internal.zmq.ZMQSocketWrapper.<init>(ZMQSocketWrapper.java:41)
org.micromanager.internal.zmq.ZMQSocketWrapper.<init>(ZMQSocketWrapper.java:45)
org.micromanager.internal.zmq.ZMQPushSocket.<init>(ZMQPushSocket.java:24)
org.micromanager.remote.RemoteStorageMonitor.<init>(RemoteStorageMonitor.java:35)
org.micromanager.remote.RemoteViewerStorageAdapter.initialize(RemoteViewerStorageAdapter.java:99)
org.micromanager.acqj.main.Acquisition.initialize(Acquisition.java:298)
org.micromanager.acqj.main.Acquisition.initialize(Acquisition.java:246)
org.micromanager.remote.RemoteAcquisition.<init>(RemoteAcquisition.java:32)
org.micromanager.remote.RemoteAcquisitionFactory.createAcquisition(RemoteAcquisitionFactory.java:53)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
org.micromanager.internal.zmq.ZMQServer.runMethod(ZMQServer.java:388)
org.micromanager.internal.zmq.ZMQServer.parseAndExecuteCommand(ZMQServer.java:466)
org.micromanager.internal.zmq.ZMQServer.lambda$initialize$2(ZMQServer.java:117)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)
```

**Comment by henrypinkard** [comment]
Is this latest pycromanager too? A similar thing was recently fixed: https://github.com/micro-manager/pycro-manager/issues/428

In general, always a good idea to update micro-manager and pycro-manager as a first step in debugging, in case its already been solved

**Comment by henrypinkard** [comment]
Hmm it doesn't reproduce for me. 

If you add a `time.sleep(10)` in between does it work?

What value of `n_frames` are you using?

Can you double check you've got the right version at runtime?
```python
from pycromanager import __version__
print (__version__)
```

Maybe its a windows thing (I'm on mac)

**Comment by henrypinkard** [comment]
and what version of `zmq`? I have:

```python
from zmq import __version__
print(__version__)
'23.2.1'
```

**Comment by Heerpa** [comment]
Yes all the versions are updated and seem correct.
The trick was to restart the computer; I did have the same alternating zmq issue before as in https://github.com/micro-manager/pycro-manager/issues/286, now it all works!
Sorry about the inconvenience, and thank you very much for helping!

**Comment by henrypinkard** [comment]
This should be less likely to happen with recent changes
