### ISSUE TITLE
Installing the wrong version on Python 3.11

### ISSUE THREAD

**Issue by bls337** [micro-manager/pycro-manager#448]
I'd like to use pycromanager with Python 3.11 but I'm encountering a problem when I install it from PyPI. I'm using Windows 10 Pro 64-bit and have encountered this issue on multiple computers.

Here are the results from running "pip install pycromanager --no-cache" in a new virtual environment (the same thing happens in the global environment):

```python
Collecting pycromanager
  Downloading pycromanager-0.20.0-py3-none-any.whl (36 kB)
Collecting numpy
  Downloading numpy-1.23.4-cp311-cp311-win_amd64.whl (14.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.6/14.6 MB 14.9 MB/s eta 0:00:00
Collecting dask[array]>=2022.2.0
  Downloading dask-2022.11.0-py3-none-any.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 17.9 MB/s eta 0:00:00
Collecting pyzmq
  Downloading pyzmq-24.0.1-cp311-cp311-win_amd64.whl (990 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 990.3/990.3 kB 15.6 MB/s eta 0:00:00
Collecting pycromanager
  Downloading pycromanager-0.19.2-py3-none-any.whl (36 kB)
  Downloading pycromanager-0.19.1-py3-none-any.whl (36 kB)
  Downloading pycromanager-0.19.0-py3-none-any.whl (36 kB)
  Downloading pycromanager-0.18.3-py3-none-any.whl (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.4/53.4 kB ? eta 0:00:00
  Downloading pycromanager-0.18.2-py3-none-any.whl (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.3/53.3 kB ? eta 0:00:00
  Downloading pycromanager-0.18.1-py3-none-any.whl (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.3/53.3 kB ? eta 0:00:00
  Downloading pycromanager-0.18.0-py3-none-any.whl (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.3/53.3 kB 2.9 MB/s eta 0:00:00
  Downloading pycromanager-0.17.10-py3-none-any.whl (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.2/53.2 kB ? eta 0:00:00
  Downloading pycromanager-0.17.9-py3-none-any.whl (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.2/53.2 kB ? eta 0:00:00
  Downloading pycromanager-0.17.8-py3-none-any.whl (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.2/53.2 kB ? eta 0:00:00
  Downloading pycromanager-0.17.6-py3-none-any.whl (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.2/53.2 kB ? eta 0:00:00
  Downloading pycromanager-0.17.5-py3-none-any.whl (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.2/53.2 kB ? eta 0:00:00
  Downloading pycromanager-0.17.4-py3-none-any.whl (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.1/53.1 kB ? eta 0:00:00
  Downloading pycromanager-0.17.3-py3-none-any.whl (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.2/53.2 kB ? eta 0:00:00
  Downloading pycromanager-0.17.2-py3-none-any.whl (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.0/53.0 kB ? eta 0:00:00
  Downloading pycromanager-0.17.1-py3-none-any.whl (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.0/53.0 kB ? eta 0:00:00
  Downloading pycromanager-0.17.0-py3-none-any.whl (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.9/52.9 kB ? eta 0:00:00
  Downloading pycromanager-0.16.6-py3-none-any.whl (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.1/52.1 kB ? eta 0:00:00
  Downloading pycromanager-0.16.5-py3-none-any.whl (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.1/52.1 kB ? eta 0:00:00
  Downloading pycromanager-0.16.4-py3-none-any.whl (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.1/52.1 kB ? eta 0:00:00
Collecting zmq
  Downloading zmq-0.0.0.zip (2.2 kB)
  Preparing metadata (setup.py) ... done
Collecting click>=7.0
  Downloading click-8.1.3-py3-none-any.whl (96 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 kB ? eta 0:00:00
Collecting cloudpickle>=1.1.1
  Downloading cloudpickle-2.2.0-py3-none-any.whl (25 kB)
Collecting fsspec>=0.6.0
  Downloading fsspec-2022.11.0-py3-none-any.whl (139 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.5/139.5 kB ? eta 0:00:00
Collecting packaging>=20.0
  Downloading packaging-21.3-py3-none-any.whl (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.8/40.8 kB ? eta 0:00:00
Collecting partd>=0.3.10
  Downloading partd-1.3.0-py3-none-any.whl (18 kB)
Collecting pyyaml>=5.3.1
  Downloading PyYAML-6.0-cp311-cp311-win_amd64.whl (143 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.2/143.2 kB 8.3 MB/s eta 0:00:00
Collecting toolz>=0.8.2
  Downloading toolz-0.12.0-py3-none-any.whl (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.8/55.8 kB ? eta 0:00:00
Collecting colorama
  Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Downloading pyparsing-3.0.9-py3-none-any.whl (98 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.3/98.3 kB ? eta 0:00:00
Collecting locket
  Downloading locket-1.0.0-py2.py3-none-any.whl (4.4 kB)
Installing collected packages: toolz, pyzmq, pyyaml, pyparsing, numpy, locket, fsspec, colorama, cloudpickle, zmq, partd, packaging, click, dask, pycromanager
  DEPRECATION: zmq is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for zmq ... done
Successfully installed click-8.1.3 cloudpickle-2.2.0 colorama-0.4.6 dask-2022.11.0 fsspec-2022.11.0 locket-1.0.0 numpy-1.23.4 packaging-21.3 partd-1.3.0 pycromanager-0.16.4 pyparsing-3.0.9 pyyaml-6.0 pyzmq-24.0.1 toolz-0.12.0 zmq-0.0.0
```

After that it says that I have version 0.16.4 installed when I use "pip list".

And when I use "import pycromanager" to use the version it says it installed I get this error:

```python
Traceback (most recent call last):
  File "C:\Users\Brandon\Desktop\UpdatePythonPackages\main.py", line 9, in <module>
    import pycromanager
  File "C:\Python\Lib\site-packages\pycromanager\__init__.py", line 3, in <module>
    from pycromanager.acquisitions import Acquisition, MagellanAcquisition, XYTiledAcquisition
  File "C:\Python\Lib\site-packages\pycromanager\acquisitions.py", line 12, in <module>
    from docstring_inheritance import NumpyDocstringInheritanceMeta
ModuleNotFoundError: No module named 'docstring_inheritance'
```

If I run "pip install pycromanager --upgrade" it tries to update me to 0.20.0 but does the same thing as before and ends up on 0.16.4.

**Comment by henrypinkard** [comment]
The dependency [got updated](https://github.com/AntoineD/docstring-inheritance/issues/2). Can you try installing again?

**Comment by bls337** [comment]
It worked on two different Windows 10 64-bit computers for me, I can install 0.20.0 now. Thanks!
