### ISSUE TITLE
Calling Core methods in different thread fails due to AttributeError in _Bridge.__new__.

### ISSUE THREAD

**Issue by Ostheer** [micro-manager/pycro-manager#555]
### Bug report

**Bug summary**

I want to run some sweeps in a background thread. I create the `core = Core()` object in the main thread, and then call some member methods of `core` in a separate thread. These calls fail, because `_Bridge.__new__` raises an `AttributeError`.

Minimal Example:
```python
from pycromanager import Core
import threading
core = Core()
def tf():
    core.get_property("Camera", "Exposure")
threading.Thread(target=tf).start()
```

**Expected outcome**

The `Camera.Exposure` property is retrieved.

**Actual outcome**

Exception in thread, see traceback below.

Without thinking too much I was able to seemingly successfully work around the issue by adding the following clause directly after the line that says `with _Bridge._bridge_creation_lock:`:
```python
if not hasattr(_Bridge.local, "cached_bridges_by_port"):
    _Bridge.local.cached_bridges_by_port = {}
```
But I don't know if this secretly fucks up everything under the hood.

```
Exception in thread Thread-5 (tf):
Traceback (most recent call last):
  File "[/usr/lib/python3.10/threading.py](https://file+.vscode-resource.vscode-cdn.net/usr/lib/python3.10/threading.py)", line 1016, in _bootstrap_inner
    self.run()
  File "[/usr/lib/python3.10/threading.py](https://file+.vscode-resource.vscode-cdn.net/usr/lib/python3.10/threading.py)", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-6-ddee6c15c423>", line 5, in tf
  File "[/home/mathijsv/Documents/git/pycropoc/venv/lib/python3.10/site-packages/pycromanager/zmq_bridge/_bridge.py](https://file+.vscode-resource.vscode-cdn.net/home/mathijsv/Documents/git/pycropoc/venv/lib/python3.10/site-packages/pycromanager/zmq_bridge/_bridge.py)", line 465, in <lambda>
    ): instance._translate_call(signatures_list, args, static=_java_class == 'java.lang.Class')
  File "[/home/mathijsv/Documents/git/pycropoc/venv/lib/python3.10/site-packages/pycromanager/zmq_bridge/_bridge.py](https://file+.vscode-resource.vscode-cdn.net/home/mathijsv/Documents/git/pycropoc/venv/lib/python3.10/site-packages/pycromanager/zmq_bridge/_bridge.py)", line 678, in _translate_call
    self._send(message)
  File "[/home/mathijsv/Documents/git/pycropoc/venv/lib/python3.10/site-packages/pycromanager/zmq_bridge/_bridge.py](https://file+.vscode-resource.vscode-cdn.net/home/mathijsv/Documents/git/pycropoc/venv/lib/python3.10/site-packages/pycromanager/zmq_bridge/_bridge.py)", line 566, in _send
    return self._get_bridge()._send(message)
  File "[/home/mathijsv/Documents/git/pycropoc/venv/lib/python3.10/site-packages/pycromanager/zmq_bridge/_bridge.py](https://file+.vscode-resource.vscode-cdn.net/home/mathijsv/Documents/git/pycropoc/venv/lib/python3.10/site-packages/pycromanager/zmq_bridge/_bridge.py)", line 592, in _get_bridge
    bridge_to_use = _Bridge(
  File "[/home/mathijsv/Documents/git/pycropoc/venv/lib/python3.10/site-packages/pycromanager/zmq_bridge/_bridge.py](https://file+.vscode-resource.vscode-cdn.net/home/mathijsv/Documents/git/pycropoc/venv/lib/python3.10/site-packages/pycromanager/zmq_bridge/_bridge.py)", line 233, in __new__
    if port in _Bridge.local.cached_bridges_by_port:
AttributeError: '_thread._local' object has no attribute 'cached_bridges_by_port'
```

**Version Info**
I'm running the MicroManager server on a remote windows machine while I use pycromanager from my Linux desktop. Port 4827 is tunneled over SSH. For the minimal example, I installed the MicroManager server (from the exact same installer binary) on my Linux Desktop (using Wine) and the error was identical.

Server
  * Operating system: Windows 10
  * pycromanager version: N/A
  * MicroManager version: "MM Studio": 2.0.0, "MMCore": 10.1.1
  * Python version: N/A
  * Python environment (command line, IDE, Jupyter notebook, etc): N/A

Client
  * Operating system: Arch Linux (6.2)
  * pycromanager version: 0.26.0
  * MicroManager version: N/A
  * Python version: 3.10.9
  * Python environment (command line, IDE, Jupyter notebook, etc): any

**Comment by henrypinkard** [comment]
Ok I think this is fixed now

https://github.com/micro-manager/pycro-manager/pull/558
