### ISSUE TITLE
Potential race condition in the Bridge

### ISSUE THREAD

**Issue by henrypinkard** [micro-manager/pycro-manager#635]
As of now, unclear how to reliably reproduce

I've seen this twice now, and both times I think it occurred at shutdown of the process since it runs in the destructor and so it hasn't caused any problems. If anyone else sees it it'd be good to know if it only occurs in that situation

```
 Exception ignored in: <function _JavaObjectShadow.__del__ at 0x00000253FF43A8B0>
Traceback (most recent call last):
  File "D:\a\pycro-manager\pycro-manager\pycromanager\zmq_bridge\_bridge.py", line 643, in __del__
    self._close()
  File "D:\a\pycro-manager\pycro-manager\pycromanager\zmq_bridge\_bridge.py", line 567, in _close
    self._send(message)
  File "D:\a\pycro-manager\pycro-manager\pycromanager\zmq_bridge\_bridge.py", line 581, in _send
    return self._get_bridge()._send(message)
  File "D:\a\pycro-manager\pycro-manager\pycromanager\zmq_bridge\_bridge.py", line 329, in _send
    return self._main_socket.send(message, timeout=timeout)
  File "D:\a\pycro-manager\pycro-manager\pycromanager\zmq_bridge\_bridge.py", line 120, in send
    raise Exception("Tried to send message through socket {}, which is already closed".format(self._port))
Exception: Tried to send message through socket 4827, which is already closed
```

**Comment by henrypinkard** [comment]
I think I was able to reproduce this by running in run instead of debug mode, and I think it is now solved
