### ISSUE TITLE
Incorrect arguments exception

### ISSUE THREAD

**Issue by ilyakolb** [micro-manager/pycro-manager#67]
I am running this simple code to move the stage in XY:

```
from pycromanager import Bridge

bridge = Bridge()
core = bridge.get_core()

core.set_relative_xy_position(core.get_xy_stage_device(), 100.0, 0)
```

I am getting the following error:

```
Exception: Incorrect arguments.
Expected double, double or java.lang.String, double, double
Got <class 'str'>, <class 'int'>, <class 'int'>
```

This worked OK a few commits ago (late June). Any ideas?

**Comment by henrypinkard** [comment]
This is because the third argument is you pass is a python int, and a java double is expected. Change from `0` to `0.` would fix this, but I just added in autoconversion to new version (https://github.com/micro-manager/pycro-manager/pull/68) so this shouldn't be a concern in the future

**Comment by wl-stepp** [comment]
I'm having a similar issue with a 'java.lang.Double'
My final setup is a little more complicated, but this gives the same error message for me:
```
from pycromanager import Bridge
bridge = Bridge()

image = bridge.get_studio().acquisitions().snap().get(0)
builder = bridge.get_studio().acquisitions().generate_metadata(image, False).copy_builder_preserving_uuid()
builder.elapsed_time_ms(100.)
```

This gives the error

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\Users\stepp\Documents\05_Software\isimgui\isimgui-venv\lib\site-packages\pycromanager\core.py", line 399, in <lambda>
    ): instance._translate_call(signatures_list, args)
  File "c:\Users\stepp\Documents\05_Software\isimgui\isimgui-venv\lib\site-packages\pycromanager\core.py", line 507, in _translate_call
    valid_method_spec, deserialize_types = _check_method_args(method_specs, fn_args)
  File "c:\Users\stepp\Documents\05_Software\isimgui\isimgui-venv\lib\site-packages\pycromanager\core.py", line 664, in _check_method_args
    if _check_single_method_spec(method_spec, fn_args):
  File "c:\Users\stepp\Documents\05_Software\isimgui\isimgui-venv\lib\site-packages\pycromanager\core.py", line 639, in _check_single_method_spec
    for acceptable_type in _JAVA_TYPE_NAME_TO_CASTABLE_PYTHON_TYPE[arg_java_type]
KeyError: 'java.lang.Double'
```
I thought I would add java.lang.Double to the castable types, just as java.lang.String is already by adding it to:
_CLASS_NAME_MAPPING
_JAVA_TYPE_NAME_TO_PYTHON_TYPE
_JAVA_TYPE_NAME_TO_CASTABLE_PYTHON_TYPE
_JAVA_NON_PRIMITIVES

But I realize, that the java side also has to know about it. So I think getParamCombos would have to deal with this, just as it has a special case for java.lang.String?
The error message after the modification in core.py is
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\Users\stepp\Documents\05_Software\isimgui\isimgui-venv\lib\site-packages\pycromanager\core.py", line 434, in <lambda>
    ): instance._translate_call(signatures_list, args)
  File "c:\Users\stepp\Documents\05_Software\isimgui\isimgui-venv\lib\site-packages\pycromanager\core.py", line 556, in _translate_call
    return self._deserialize(self._socket.receive())
  File "c:\Users\stepp\Documents\05_Software\isimgui\isimgui-venv\lib\site-packages\pycromanager\core.py", line 169, in receive
    self._check_exception(message)
  File "c:\Users\stepp\Documents\05_Software\isimgui\isimgui-venv\lib\site-packages\pycromanager\core.py", line 174, in _check_exception
    raise Exception(response["value"])
Exception: java.lang.NullPointerException
	at java.lang.Class.isAssignableFrom(Native Method)
	at org.micromanager.internal.zmq.ZMQServer.runMethod(ZMQServer.java:352)
	at org.micromanager.internal.zmq.ZMQServer.parseAndExecuteCommand(ZMQServer.java:426)
	at org.micromanager.internal.zmq.ZMQServer.lambda$initialize$1(ZMQServer.java:111)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Let me know if there is an easier way to change the metadata on an image from python, I might be stuck with my head in the sand.

Thanks!

**Comment by henrypinkard** [comment]
Yeah there's some convoluted conversion between `double` and `Double`that needs to happen somewhere.

Could you just ditch the studio and use the core directly?

```python
with Bridge() as bridge:
    # get object representing micro-manager core
    core = bridge.get_core()
    core.snap_image()
    tagged_image = core.get_tagged_image()
    pixels = np.reshape(
        tagged_image.pix, newshape=[tagged_image.tags["Height"], tagged_image.tags["Width"]]
    )
    metadata = tagged_image.tags

**Comment by wl-stepp** [comment]
Thanks for the reply.

I can't really use the tagged_image.
The metadata does not have the elapsedTImeMs field yet. So if I convert that image the resulting studio image will also not have the elapsed time. Ok I would have to handle that in the receiving side of the images to read out from the core metadata instead of the elapsedTimeMs.
I tried to modify the tags in the tagged_image, but they are directly represented as a dict, so java does not know that I modified them. I could construct a new taggedImage maybe with my own metadata as a json string, but to pass that I would need to get a 'mmcorej.org.json.JSONObject' to pass. Again, I can't construct that:

`bridge.construct_java_object('mmcorej.org.json.JSONObject', args=[json.dumps(metadata)])`

gives

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\Users\stepp\Documents\05_Software\isimgui\isimgui-venv\lib\site-packages\pycromanager\core.py", line 345, in construct_java_object
    return self._class_factory.create(
  File "c:\Users\stepp\Documents\05_Software\isimgui\isimgui-venv\lib\site-packages\pycromanager\core.py", line 414, in create
    _interfaces = serialized_obj["interfaces"]
KeyError: 'interfaces'
```

The serialized object has only three keys and looks like this:

```
{'type': 'object', 'class': 'JSONObject', 'value': '{"Z-Description":"Demo stage driver",...
```

I'm passing the image to a ProcessorPlugin anyways, I think I can pass it a timestamp there, but would have felt cleaner to do it where I call the snap(). 
Do we know why an image called by snap() does not even have the receivedTime set? This would be another workaround. Or even to set the elapsedTime since program start or something on the snap() images. This is the case if I use live().snap(), but only if LiveMode is on....
I realize that this would be an issue for micro-manager, sorry.

Thank You for the help. Much appreciated.

**Comment by henrypinkard** [comment]
> Again, I can't construct that:
> 
> `bridge.construct_java_object('mmcorej.org.json.JSONObject', args=[json.dumps(metadata)])`

Another Bridge bug. I made issues for both of these. This is fixable, but I'm not going to have time to dig in in the near future. I am also hesitant to accept PRs on the bridge layer since everything is built upon it and it doesnt have a proper testing framework in place to ensure things dont accidentally break.

> Ok I would have to handle that in the receiving side of the images to read out from the core metadata instead of the elapsedTimeMs.

This is exactly what the studio code is doing anyway Im pretty sure.


Its worth noting that the Studio API and pycromanager were designed entirely separately, hence the many weird things your running into. I would recommend switching to the `Acquisition` class: https://pycro-manager.readthedocs.io/en/latest/acq_overview.html if you can, as this will be able to accomplish pretty much everything you want to do with the studio (with the exception perhaps of live mode, but can do this yourself from python pretty easily)

**Comment by wl-stepp** [comment]
Thank you. I will have a closer look at the Acquisition class and if I can achieve everything that I want to do directly in there.
